### ISSUE TITLE
Pinball Graffiti (JPN & PAL) - Missing Graphics & some corruption

### ISSUE THREAD

**Issue by Kikusui1** [MiSTer-devel/Saturn_MiSTer#103]
On both the Japanese & European PAL versions of Pinball Graffiti there are issues displaying the "background graphics" / pinball table art resulting in a black layer.

Also, some of the 3D assets also strectch across the screen. I have included screenshots from the MSTer to highlight, and included a link to gamplay on Youtube to show how it should look.

https://youtu.be/j4gle_FtwPE?feature=shared

![Piball Graffiti 1](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/434ace95-ca76-47fa-8cad-b50d44e3ad6f)
![Piball Graffiti 3](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/c582f65e-0eef-465b-8d24-780c3f42dad7)
![Pinball Graffiti 2](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/71b6bd71-cc4a-47e9-8e18-3260a6f1e3b8)
![Pinball Graffiti 4](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/bf0a82fc-aaf5-4c11-943f-b4913afd33e5)

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/b109f5756453c30102994ddf4fca5ef5badec876
