### ISSUE TITLE
Assault Suit Leynos 2 (Japan) // REGRESSION - The game freezes within the first seconds of gameplay during the 1st stage

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#106]
Since core 20240202, the game regressed with a crashing freeze on the first level of the game, just after 4/5 seconds of gameplay.

Confirmed with another user (230-V) on MiSTer Discord.

**Comment by Zet-sensei** [comment]
Display errors are fixed since commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/2ddd2cd1374d7fe6b757c9f3519cec84b08e4573 but the game freezes during the first seconds at the moment.

Tested with core 20240214

**Comment by real-amano** [comment]
Probably fixed today

**Comment by Zet-sensei** [comment]
Just needed some time for testing it more thoroughly.

Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/32a18147b6d84559801b4fdda307072537d688b9.
