### ISSUE TITLE
Dead or Alive (Japan) (Rev A) // Slowdowns during fights

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#107]
The game will slowdown more and more after each round.

EDIT : The first stage seems okay, the second will have some bearable slowdowns, and after the third one each move will slow down like half speed.

**Comment by Zet-sensei** [comment]
Build 20240504 seems to work better than previous ones.
Not perfect at the moment but we're getting there.

**Comment by fabrisco1** [comment]
Tried build 20240817 and the slowdown are present in every game version/revision

**Comment by Zet-sensei** [comment]
Much better since commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d7aee5703a2ff8b9829ccb1f78726b04f6031864 on a Dual RAM system.

Some lag spikes remain like on Hayabusa's stage, but I need to perform some comparison with an OG system before closing or reporting back once more.

**Comment by Zet-sensei** [comment]
Seems now on par with the real system when I've done some checks.

Only possible with a Dual RAM build.
