### ISSUE TITLE
Tokimeki Memorial - Forever with You (Japan) // Glitchy girl's arm sprite in the Konami intro

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#111]
When the hand animation comes to move down the board with the KONAMI logo (starting the game), we can see some graphical corruption for a moment.

**Comment by Zet-sensei** [comment]
Maybe checking if the issue is related to a SH-2 read/write VDP1 draw slowdown incorrectly set up during that intro.

**Comment by srg320** [comment]
> Maybe checking if the issue is related to a SH-2 read/write VDP1 draw slowdown incorrectly or non set-up during that intro.

You're right. Tokimeki Memorial, Whizz, Grandia (beginning), NBA JAM Tournament Edition (team selection screen) have the same problem. 
To accurately emulate the VRAM read slowdown when drawing I need to research this feature on real hardware. When I have a logic analyzer, I will be able to fix it. It will take time.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/ef3f47034e57be4302dfc0ad107f4441861cb979
