### ISSUE TITLE
WarCraft II - The Dark Saga (USA) // Can't boot

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#112]
The game refuses to boot after the SEGA logo from the BIOS.

**Comment by Kuba-J** [comment]
I can't reproduce it , it works on every startup ok.

https://youtu.be/obdqDQoZTLQ

**Comment by Zet-sensei** [comment]
The problem remains with a fresh dump from my disc (same hashes as a Redump one), a Redump copy from the Net in BIN/CUE and my proper CHD file from before.

On my two systems (Single 3.0 & Dual 2.9).
Core 20240204
