### ISSUE TITLE
Puyo Puyo SUN // Miscellaneous Broken Sprites 

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#114]
![Screenshot 2024-02-06 14-23-49](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/2f9f7f11-7e88-4cf9-8070-f89a876bedff)
![Screenshot 2024-02-06 14-36-00](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/7ef6de08-369b-448f-8611-b41941179302)
![Screenshot 2024-02-06 14-36-49](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/21b8f0a9-f231-4085-91a8-1e8f6cbd5f33)

In Puyo Puyo Sun, there are miscellaneous sprites that aren't displaying correctly, typically having issues like obvious splicing while scaling or has broken detailing. Tested on the Feburary 6th 2024 build with two 2.9 128MB RAM modules.

**Comment by Zet-sensei** [comment]
Core version 20240204 is displaying the sprites correctly, so commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/15f19290f95b35dc9cde7982ad43e619b1cee77d have done something wrong for that game.

**Comment by Zet-sensei** [comment]
Should be fixed with core 20240210.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-02-10 11-49-30](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/062b188f-4280-4b7c-9de4-aee4484e56dd)
Yeah the sprites are looking normal again, so I'll close this for now.
