### ISSUE TITLE
Grandia (JAP) menu issues

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#115]
- There are issues on the screen during combat - FIXED

![IMG_20240206_204042741](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/fdad3f7b-8ca6-4d7d-82e7-6ec85ded7b79)

- Character sprites look incorrect , visible in different places, or while running (maybe error with scaling): - FIXED

![IMG_20240206_204234979](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/84c1a805-03a5-4ff9-ad15-97ed50bea1ec)

New bug: 

- Menu have errors, menu items are not well positioned:

![IMG_20240206_204300486](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/ef6d23c3-5b0a-4432-ad3b-317d5b69784d)

for reference

![refer](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/6ebba79e-26b8-4a9d-9a3e-8b0871c3a7af)

Save file: [Grandia (Japan).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14185491/Grandia.Japan.zip)

**Comment by Zet-sensei** [comment]
Seems to be related to https://github.com/MiSTer-devel/Saturn_MiSTer/issues/114 with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/15f19290f95b35dc9cde7982ad43e619b1cee77d

**Comment by Kuba-J** [comment]
on core 202402024 battles, and sprites looks fine

**Comment by Kuba-J** [comment]
battles and sprites fixed , core 20240210

Menu still have issues.

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f519e4d446e0692c4b3fcdd202bf6c8aaf5cd2b7
