### ISSUE TITLE
In The Hunt (Us) not working in 20240206 version and 20240204 version

### ISSUE THREAD

**Issue by gomadosnitro** [MiSTer-devel/Saturn_MiSTer#116]
In The Hunt Us not working in 20240206 version and 20240204 version, was working in 20240202 and past releases.

**Comment by odiaboeeu** [comment]
The American version has a bug that if it is not below 98 or second controller connected it does not start. 

I just tested it with date 1994 and started the game

**Comment by gomadosnitro** [comment]
Interesting but dont kwow why is working With 20240202 and earlier Reléases.

**Comment by odiaboeeu** [comment]
I haven't followed all the changes here in git, but I think something of the internal clock has been implemented, when I accessed it was 2024 the date

**Comment by Kuba-J** [comment]
A few weeks ago also had to turn off controller 2 for the game to start. I don't know what changes cause the game to launch once and not , but it's a known problem from real hw

**Comment by Zet-sensei** [comment]
The original game have two major bugs :
- The game can't pass the KOKOPELI logo if two controllers are connected on the system (similar original hardware bug with Shinobi-X);
- The game have a Y2K bug - if the RTC is set with a year greater than 1999, the game refuses to boot on original systems.

When introducing the RTC commit, the second bug have emerged & you need to set the real time clock -inside the BIOS-, like on a real system.

So the issue should be classified as original hardware bug, not a core one.

**Comment by gomadosnitro** [comment]
Ok i understand the problem, it seems not working because the core its even more close to real hardware.

**Comment by gomadosnitro** [comment]
Ok i understand the problem, it seems not working because the core its even more close to real hardware.

**Comment by gomadosnitro** [comment]
Ok i understand the problem, it seems not working because the core its even more close to real hardware.
