### ISSUE TITLE
Multiple games // REGRESSION - SMPC - Controls are broken (multiple inputs at the same time) or don't respond anymore

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#118]
Since core 20240204, Rayman (USA) have broken controls.

**Comment by Zet-sensei** [comment]
I've seen a similar bug long ago on software emulators that was affecting probably the SCU interrupt mask mechanism.

So maybe checking on the changes from commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/e5b5642f590ebdbccaf17e3c0445d00cfbeb6f9b will be interesting for that issue.

**Comment by Zet-sensei** [comment]
When doing some tests, the last working version was core 20240202.

The changes on the SMPC with the INTBACK command must have broken something.
Maybe taking a look if the correct SF register value is set and/or acknowledging a INTBACK_BREAK only after the first INTBACK command have been processed.

**Comment by Zet-sensei** [comment]
After some other reports by users on Discord, at least these games are affected :
- Guardian Heroes;
- Worms;
- Corpse Killer;
- Rayman;
- Three Dirty Dwarves

**Comment by real-amano** [comment]
Worms and Corpse Killers were outlined in #121 (closed for this bug now)

**Comment by Zet-sensei** [comment]
Reverting the SMPC code to a previous state (20240202) & only adding the delay on the INTBACK command fixes at least Rayman, Guardian Heroes and Three Dirty Dwarves.
Without breaking Terry Pratchett's Discworld once more.

I'm waiting for some reports on the other impacted games.

**Comment by Zet-sensei** [comment]
After some more tests, we could fix these games with reverting the SMPC changes to its state on 20240202 version & just adding `WAIT_CNT <= 20'd800;` during the INTBACK command (for Primal rage & Discworld support).

- Guardian Heroes;
- Corpse Killer;
- Rayman;
- Three Dirty Dwarves;
- Quarterback Attack with Mike Ditka.

Worms have another kind of issue and should be treated separately.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/87e4a2eade4852f625ebbbdf4fd334bc4915485d.
