### ISSUE TITLE
Guardian Heroes (USA) REGRESSION core 20240204 - 20240210

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#119]
Sometimes the game does not want to start (after the Sega logo)

The controller stops responding at different times (menu , or start of the game). Everything is also slow. 

**The game works fine with core 20240202**

**Comment by Zet-sensei** [comment]
Must be a SMPC bug introduced on core version 20240204 when doing some changes on that part of the core.

It must be better to create a meta issue with all the impacted games at https://github.com/MiSTer-devel/Saturn_MiSTer/issues/118

**Comment by Kuba-J** [comment]
Problem outlined in https://github.com/MiSTer-devel/Saturn_MiSTer/issues/118
