### ISSUE TITLE
EUR BIOS sound is incorrect

### ISSUE THREAD

**Issue by vmicka72** [MiSTer-devel/Saturn_MiSTer#12]
When arriving on the bios menu the sound is incorrect.
Normal sound when entering to bios : https://indreams.me/collection/cLSxzqXjSsT
On Japanese bios the sound is correct.

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/577c12f1f3c379f9cae8e4fdf6f69c8174d887c5
