### ISSUE TITLE
WORMS (USA ) no controller response in the menu 

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#121]
There is no controller response in the menu (tested on dual and single sdram)

core 20240210

**Comment by Kuba-J** [comment]
Corpse Killer works ok with core 20240202

**Comment by Zet-sensei** [comment]
Related to https://github.com/MiSTer-devel/Saturn_MiSTer/issues/118

Seems to be related with the SMPC changes on the 20240206 version of the core.
Maybe check on the INTBACK command changes.

**Comment by Kuba-J** [comment]
Problem outlined in https://github.com/MiSTer-devel/Saturn_MiSTer/issues/118

**Comment by Zet-sensei** [comment]
Issue should be reopened (and renamed) only for Worms at some point, as the issue isn't only about a regression on the SMPC with the last changes on 20240204.

Corpse Killers is affected by the recent regression and we could either revert the SMPC code to a previous state (like 20240202 version) or wait for a further update from srg320.

**Comment by Kuba-J** [comment]
fixed core 20240406 https://github.com/MiSTer-devel/Saturn_MiSTer/commit/61c8a8577b07d2557b1b83d374f6edf735f213e6 thanks!
