### ISSUE TITLE
Batsugun (JPN) - Graphical errors in background layer (regression)

### ISSUE THREAD

**Issue by Kikusui1** [MiSTer-devel/Saturn_MiSTer#122]
Batsugun has had a regression in that the background layer is showing graphical errors that have been introduced with the latest version of the core (20240210). These graphical errors were not present in the previous iteration of the the core (20240206).

These screenshots I have included are from the build of 20240210 ------- 
![Batsugun e - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/4be7f0cc-768a-483d-b125-ea6b296e89b3)
![Batsugun f - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/02bff138-471f-45b9-be54-b0cec7c39fe7)
![Batsugun a - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/91d2d5ab-8af4-459b-895e-762d89894813)
![Batsugun b - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/9dfaac40-21d3-4bfd-94f3-22d14e424135)
![Batsugun c - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/279aced0-ed97-48d4-8335-5cdd639d1bcf)
![Batsugun d - core 20240210](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/674abe8b-1d7d-425e-b443-cc0c4b5b71cc)

The screenshots below are from the previous build (20240206) for comparison.

![Batsugun a - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/8d2c0c9d-4673-4c00-9eee-78a6882c6f3a)
![Batsugun b - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/72b0c47a-7e70-4996-9da5-2791ab14db1f)
![Batsugun c - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/ba56464b-ef9d-49f1-aec8-a5496137f34d)
![Batsugun d - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/8defa6a3-b77d-4683-ba1b-c81a1dae0a88)
![Batsugun e - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/2ca72577-58e3-4faf-9204-c9227970e145)
![Batsugun f - core 20240206](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/d321786c-18ff-4c17-89a2-dc54bf24b01d)

**Comment by Zet-sensei** [comment]
Maybe a framebuffer issue or one of the VDP changeswith core revision 20240210.

Like the reintroduction of the transparency bug on Puyo Puyo Tsuu menus (please see issue https://github.com/MiSTer-devel/Saturn_MiSTer/issues/68) with the same core version.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/041bd541236eea9c1a7cf1fbdd58bcefb7bff120

**Comment by METR0lD** [comment]
Just did a full play through of loop one in Special Version with no noticeable issues. Seems good on my end as well.
