### ISSUE TITLE
Monster Slider // Loading Instability

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#123]
https://streamable.com/1gp1jc
https://streamable.com/5v8mhg

Monster Slider has a general problem where it struggles to load cutscenes. For example the cutscene where the two characters interact struggle to load the animations and text causing it to get drawn out, while matches similarly struggle to load by having the characters recite all their voice clips and drag out the scene a lot longer than intended. Also, the game is prone to randomly crashing, sometimes happening after a cutscene ends and tries to load the next one.

Tested using the February 12th 2024 build using two 2.9 128MB RAM modules.

**Comment by real-amano** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/commit/9f7a6c3124f5d0c7884882f3d1c5f964117ca814

There is a bunch of disc-loading fixes. But not on core but on main mister level. 
Thus potentially fixed if you built a new unstable Mister. Let's see when Sorgelig releases the next binary build.

**Comment by Zet-sensei** [comment]
I've done some more tests today with the last Unstable Main (20240228) + core version 20240229.

The issue remains so far.

**Comment by srg320** [comment]
Multi-index tracks are only supported for CUE/BIN format for now. I don't know how extract index data from CHD image yet.

**Comment by real-amano** [comment]
Maybe that info should be added to the readme.md to prevent further bug reports. I guess that other games might be affected as well.

**Comment by Zet-sensei** [comment]
So that issue n Rayman https://github.com/MiSTer-devel/Saturn_MiSTer/issues/141 could be related too.

**Comment by srg320** [comment]
> So that issue on Rayman #141 could be related too.

No. So far, Monster Slider is the only game I've found that contains multi-index tracks.

**Comment by Zet-sensei** [comment]
I could go to the third stage on the game with the last changes on core version 20230329 + Unstable Main MiSTer 20230331.

**Comment by real-amano** [comment]
@InfernoHabanero Do you still see the problem? Can you re-test (and close the bug?)

**Comment by real-amano** [comment]
@InfernoHabanero Do you still see the problem? Can you re-test (and close the bug?)

**Comment by real-amano** [comment]
@InfernoHabanero Do you still see the problem? Can you re-test (and close the bug?)

**Comment by real-amano** [comment]
@InfernoHabanero Do you still see the problem? Can you re-test (and close the bug?)

**Comment by real-amano** [comment]
@InfernoHabanero Do you still see the problem? Can you re-test (and close the bug?)

**Comment by Zet-sensei** [comment]
Good catch when I checked the CUE file of the game.

So far I have also checked open issues on libCHD GitHub.
The CHD format cannot recover multi-track indexes info when converting from BIN+CUE (Redump).
Multi-index information is lost and will most likely require changes from the current format to add the appropriate support.

At the time of my comment, Monster Slider & Taito Chase H.Q. must be played in BIN+CUE (Redump) format with the core.

**Comment by srg320** [comment]
List of games where tracks contain more than two indexes:
AI Shougi 2 (Japan).zip
Dark Savior (Europe).zip
Dark Savior (Japan).zip
Dark Savior (USA).zip
Flash SegaSaturn Vol. 14 (Japan).zip
Gaia Breeder (Japan).zip
Honkaku Hanafuda (Japan).zip
Magical Drop (Japan).zip
Mahjong Taikai II Special (Japan) (2M).zip
Mahjong Taikai II Special (Japan) (Rev A) (10M).zip
Minnesota Fats - Pool Legend (USA) (R).zip
Monster Slider (Japan).zip
Nanatsu no Hikan (Japan) (Disc 1) (1M).zip
Nanatsu no Hikan (Japan) (Disc 1) (2M).zip
Nanatsu no Hikan (Japan) (Disc 2) (2M).zip
Nanatsu no Hikan (Japan) (Disc 3) (1M, 2M).zip
NBA Action (Europe).zip
NBA Action (USA).zip
PriCla (Princess Clara) Daisakusen (Japan).zip
Saturn Super Vol. 4 (Japan) (2M).zip
Side Pocket 2 - Densetsu no Hustler (Japan).zip
Space Jam (Europe).zip
Space Jam (Japan).zip
Space Jam (USA).zip
Striker '96 (Japan) (En,Fr,De,Es,It).zip
Striker '96 (USA).zip
Striker 96 (Europe) (En,Fr,De,Es,It).zip
Suiko Enbu - Fuuun Saiki (Japan).zip
Taito Chase H.Q. + S.C.I. (Japan).zip
Virtual Casino (Japan).zip
Voice Idol Maniacs - Pool Bar Story (Japan) (Disc 1) (2M).zip
WWF In Your House (Europe).zip
WWF In Your House (Japan).zip
WWF In Your House (USA).zip
WWF WrestleMania - The Arcade Game (Europe).zip
WWF WrestleMania - The Arcade Game (Japan).zip
WWF WrestleMania - The Arcade Game (USA).zip

**Comment by Zet-sensei** [comment]
Thanks for the list, I will inform the other testers.

For documentation, the original issue on MAME Github.
https://github.com/mamedev/mame/issues/10308

**Comment by real-amano** [comment]
Maybe this list should be added to the Readme.md.

That all those are not CHD compatible.
