### ISSUE TITLE
Yumimi Mix Remix // Graphics Not Loading

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#125]
![Screenshot 2024-02-13 09-59-53](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/977a3b90-e84c-4baf-80c8-a96da08245a8)
![Screenshot 2024-02-13 10-00-40](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/d54aad0c-b99e-41eb-92a5-4a1b075c22c4)
![Screenshot 2024-02-13 10-03-37](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/83b856b8-286b-4235-b99f-520bababdcc1)

Yumimi Mix Remix fails to load multiple sprites, most of which are backgrounds, but sometimes it also affects other stuff like the characters. It's otherwise playable.

Tested using the February 12th 2024 build using two 2.9 128MB RAM modules.

**Comment by Zet-sensei** [comment]
Version 20240210 works as intended, recent regression.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-02-15 12-21-54](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/610e3326-15b1-43e7-9f1d-141df4e38c06)

Fixed in the February 14th 2024 build!
