### ISSUE TITLE
Astal (USA) // Sound stutters on second part of the first stage

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#128]
The sound is stuttering on the second part of the first stage, after saving the bird and before entering the cavern.

Regression that seemed to begin weeks ago, I cannot retrace the exact core version at the moment.

Confirmed by multiple users.

**Comment by real-amano** [comment]
Is Astal booting? See issue #117

**Comment by Zet-sensei** [comment]
The 1S and 2S versions are mostly affected by the regressions on booting by the SMPC changes.
The 3S version could boot if after another game is launched before.
If I revert the SMPC module code to the 20240202 version, I could make them boot normally once again.

I've created this second separate issue as the regression on sound is older (and was never repored before) than the SMPC changes and distinct from the other issue.

**Comment by JaeOfMordor** [comment]
an update to MiSTer main, that can be found under unstable-nightlies on the discord, has fixed this. I've just played and confirmed myself. 

congrats to srg320 again

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Main_MiSTer/commit/74d819b35ac3151aff0dc86874aafac21e07a9aa
