### ISSUE TITLE
Inaccurate CDDA track reading compared to real hardware

### ISSUE THREAD

**Issue by protogem2** [MiSTer-devel/Saturn_MiSTer#13]
Games which have had their CDDA tracks replaced do not have the tracks read correctly on the MiSTer core, while they are read correctly on original Saturn hardware. The MiSTer is playing the tracks with pops/clicks while an original Saturn using a MODE ODE or burned disc do not. Here are 3 videos to help demonstrate the problem:

Game with changed CDDA tracks loading on MiSTer:

https://youtu.be/Mg_Bch2wnWk?si=V8sXXA85hnACcKfT

Game with changed CDDA tracks loading on a Sega Saturn from a burned CD:

https://youtu.be/RoFnDJ2TsdY?si=OvZBju37zVL363r_

Game with changed CDDA tracks loading on a Sega Saturn from a MODE ODE:

https://youtu.be/rG_OY-OAAWg?si=3PbKgJATtCUlrFy1

When the track is played on MiSTer a pop/click happens. I am using the latest (of the time of this issue being posted) single SDRAM Saturn core.

**Comment by InfernoHabanero** [comment]
Maybe the inaccurate CDDA is why some games have issues with the volume being lower than it should? Because a common thing they share is having that popping noise before the audio loads.

**Comment by Zet-sensei** [comment]
A retest will be necessary as an upcoming PR (MiSTer-devel/Main_MiSTer#880) on the Main MiSTer have some CDDA changes.
