### ISSUE TITLE
Burning Rangers (USA) , Issues with transaparent sprites

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#132]
A decoding error on the VDP2 NBG1 with transparent sprites. (thanks Zet-sensei)

![sprites transparent](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/bf7c1313-d6f8-4271-b3dc-0a5546fc1e73)

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/5b8742dd-b996-4abc-bcc0-d5e7d007a966

save [Burning Rangers (USA).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14302406/Burning.Rangers.USA.zip)

**Comment by real-amano** [comment]
According to the changrlog today it was a VDP1 issue (12 bits were necessary for this effect).

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/fc957af249db9a1e0d8bffef2b66f0a55683b994
