### ISSUE TITLE
Soukyuu Gurentai - graphical errors with text

### ISSUE THREAD

**Issue by Kikusui1** [MiSTer-devel/Saturn_MiSTer#134]
Soukyuu Gurentai (Rev A JPN) is currently showing graphical errors with text (and possibly tile sets in the opening level with things that look like multiple white letter "T" at the top of the screen. This is while using the latest 20240215 build of the core, single sdram v3.0.

I have taken photos of the game running on real hardware as well as the MiSTer in roughly the same spots to highlight the issues. (Apologies about image quality, I forgot to use the MiSTer Remote screenshot option).

MiSTer Screenshots Below

![IMG20240216225954](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/a53d5df5-1992-4432-acf0-b92550aeb5a7)
![IMG20240216225857](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/55a8303b-610f-44ae-854f-c37ab0c4d031)
![IMG20240216230055](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/ca2bb96f-5bb0-401c-95ce-a77c591c2043)

Sega Saturn Real Hardware Screenshots Below

![IMG20240216225634](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/f4963991-ee30-4c20-b2da-1ebd6ae39bff)
![IMG20240216225527](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/56520898/603bf605-5e2d-40c9-8a36-86a056d727da)

**Comment by Zet-sensei** [comment]
I can't seem to reproduce the error on my systems (either Single & Dual RAM v2.9) with core version 20240217.

Could you retry with that version ?

**Comment by Retro-Nerd** [comment]
I've tested with today single ram udpate. I don't get this specific kind of garbage. But two rows of of the number "4" on the top screen.  Look very strange.

**Comment by Kikusui1** [comment]
I've done a bit more testing with today's revised core - 20240217 (and also the previous 20240215), here are my findings.

Single SDRAM 3.0
Region Free Hi Saturn Bios  with region set to USA in core options - the text is corrupted as highlighted in the images above.

Region Free Hi Saturn Bios with region set to Japan is core options - the text is displaying correctly as one would expect.

Region Free USA Bios with region set to USA in core options - text is garbled, even worse than in the pictures above

Region Free USA Bios with region set to Japan in core options - text is displaying correctly as one would expect.

Conclusion - this game needs to be played with the region set to Japan in the core options.

At the moment, I'm unsure whether to close this issue or not. Further comments welcome!

**Comment by real-amano** [comment]
If the game works on a baremetal USA console I would consider it a bug. If it doesn't it should be closed for good.

**Comment by Kuba-J** [comment]
The same error is on real hardware 

![Screenshot_20240218-093408](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/9f55713e-b437-428a-bc14-256df3dfd662)
