### ISSUE TITLE
Gex (USA) no music in game

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#135]
Sounds work in the game , but there is no music

core 20240217 dualsdram

**Comment by odiaboeeu** [comment]
I just tested with this latest version single sdram and the song is working

**Comment by Kuba-J** [comment]
no music here - menu or in game

**Comment by odiaboeeu** [comment]
https://www.youtube.com/watch?v=fNMI1ZMvamo

**Comment by Kuba-J** [comment]
false alarm, after resetting the settings everything works as expected. I apologize and thank you for your help.
