### ISSUE TITLE
Sega Ages OutRun Regression 20240217

### ISSUE THREAD

**Issue by FalafellGB** [MiSTer-devel/Saturn_MiSTer#137]
On the latest test build the game only renders the road and no other graphics. 

Was working fine on all the previous builds

**Comment by Zet-sensei** [comment]
The regression appeared between February 14th build and February 15th one.

**Comment by FalafellGB** [comment]
It still works on the previous build or did for me On 20 Feb 2024 10:25 am, Zet-sensei ***@***.***> wrote:
The regression appeared between February 14th build and February 15th one.

**Comment by asturur** [comment]
I experienced the same, but didn't report since i have an unsupported model of memory.
But i m glad is not an issue with my mister

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/593adc3810ee63e43b0a61204e38f57acab14e63

**Comment by real-amano** [comment]
Can be closed?

**Comment by real-amano** [comment]
@FalafellGB , can you close the issue?

**Comment by FalafellGB** [comment]
Sorry i forgot about this, will close now
