### ISSUE TITLE
Slayers Royal // Broken Animations

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#139]
https://streamable.com/u4io8h

Slayers Royal has an issue where miscellaneous animations don't render properly, like the boss in the above video using the generic physical attack flying all over the screen.

Tested on the February 22nd 2024 build using two 2.9 128MB RAM modules.

**Comment by srg320** [comment]
How to reproduce this issue?

**Comment by InfernoHabanero** [comment]
> How to reproduce this issue?

All I did was enter a battle and let it play out automatically using the characters AI. You are guaranteed to encounter this boss by leaving town for the first time by clicking the icon on the map that looks like a cave, and moving on the overworld. The battle is pretty scripted (Lina will nuke most of the enemies on her first turn for example) so it shouldn't be hard to replicate.

**Comment by srg320** [comment]
But how to enter the battle?

**Comment by InfernoHabanero** [comment]
> But how to enter the battle?

Okay so when you start fresh from a new game, you'll be in a restaurant with a cutscene that quickly introduces you to Lina Inverse, Gourry Gabriev, and Naga the Serpent. There will be a selection between two choices during this scene, but you can skip it as all it does is provide more context behind who Naga is. The second choice is just a quick rundown of the controls, which again you can skip if you want.

![Screenshot 2024-02-25 10-56-13](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/4b2190d8-28cf-4ece-9cbb-a5a296b6d4e0)

You can't leave the restaurant until you talk to this specific NPC with the pink shirt. Press the A button to talk to him for some exposition, and then select the first choice on the dialogue selection. 

![Screenshot 2024-02-25 10-59-46](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/c44e9080-bba8-4eb1-adbd-929be5960278)
![Screenshot 2024-02-25 11-00-32](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/d0de7f80-14e9-4c84-96ea-11717ebe6ef2)

Afterwards press on the B button to pull up your options, and then select this icon of the guy walking on the top using the C button. It should pull up a map with three choices. Choose the center of town that the screenshot above is highlighting and then press C.

![Screenshot 2024-02-25 11-03-12](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/0bfea446-e147-47dc-8adb-dc60afc5ed3d)

Once you enter town, there will be a small cutscene with the three characters, then the map will be updated with several more choices. Select the one on the bottom right that looks like mountains.

![Screenshot 2024-02-25 11-05-07](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/97dba71c-3b88-45b8-9474-d24336057486)

You will now be on the overworld map. All you need to do is press the C button and you will move to the next area, but then get interrupted by a cutscene. You can skip the cutscene by pressing Start, once you do you'll enter a battle.

![Screenshot 2024-02-25 11-06-46](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/fe861ff4-fcfb-4714-b62f-df557d6d9001)
![Screenshot 2024-02-25 11-07-14](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/11db15f3-38d1-4307-b474-613f34c9b891)

During this fight, press the B button to pull up the options and click the first icon that is a clock to automatically make your characters make their choices.

Hopefully this quick guide helps out.

**Comment by real-amano** [comment]
Srg  could obviously reproduce the issue. The changelog today indicates that this is fixed.

**Comment by InfernoHabanero** [comment]
Yup, animations are fixed now. Nice.
