### ISSUE TITLE
Rayman (USA) // REGRESSION - Missing some CDDA audio frames when reading some tracks (CHD only)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#141]
With recent changes to SCSP (commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f0aa89a9d7e4be232a237c053d9aa438bff9b5fe), CDDA tracks in several games like Rayman (one of the most striking examples) are now played with some audio frames too late.

Confirmed also by another user on Discord.

Tested with Main MiSTer Unstable version 2024-02-28 and core version 2024-02-29

**Comment by Zet-sensei** [comment]
Further investigations are necessary.
Will update the problem report accordingly.

**Comment by Zet-sensei** [comment]
After some more tests, the recent commit (2024-02-28) on Main MiSTer should be at fault https://github.com/MiSTer-devel/Main_MiSTer/commit/29fb8196ac8d97efd64be0c96571e3fab92c4593

If I revert to MiSTer Unstable Main 20240225, the issue is gone.
And if a try once more to change back to MiSTer Unstable Main 20240229, the problem reappears.


Tested with a CHD version of the game.

**Comment by Zet-sensei** [comment]
After some tests with a Redump formated version of the game, the issue isn't present anymore (decompressing the same CHD file to multiple BIN files + single CUE file).

Reverting to a 2024-02-05 version of the Main MiSTer file, we could load the two versions of the game without the issue too.

So, there could be something to check on the CHD part with the recent changes (2024-02-28) on that Main MiSTer file.

**Comment by real-amano** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/pull/879 
CHD compatibility seems to be in place now.

**Comment by Zet-sensei** [comment]
Not fixed for both issues.
I'm already checking regulary my opened issues, thanks.

**Comment by Zet-sensei** [comment]
Tested and confirmed as fixed with a upcoming PR (https://github.com/MiSTer-devel/Main_MiSTer/pull/880) on the Main MiSTer file.
