### ISSUE TITLE
Virtual On crackling audio regression v240304

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#143]
Virtual on’s large explosion sound effects cause lots of audio crackling and distortion.  A good example is Dorcas’ major bombing attack.  Earlier released versions did not have this problem.
Tested on v240304

**Comment by Kuba-J** [comment]
It was already reported here: https://github.com/MiSTer-devel/Saturn_MiSTer/issues/9#issuecomment-1971802208

**Comment by Kuba-J** [comment]
https://github.com/MiSTer-devel/Saturn_MiSTer/commit/577c12f1f3c379f9cae8e4fdf6f69c8174d887c5

**Comment by real-amano** [comment]
@gleek12 , can you re-test and close this issue?

**Comment by gleek12** [comment]
Tested!  The issue appears to be gone!  Thank you!!
