### ISSUE TITLE
[FEATURE REQUEST] (Shuttle) Mouse support

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#146]
Some users have asked on the Discord if it would be possible to support the Shuttle mouse (or even just a more basic mouse) on the core in the future.

**Comment by Zet-sensei** [comment]
Could be done with a SNAC build for the original Shuttle mouse.

**Comment by RGarciaLago** [comment]
There are 115 Saturn games that feature mouse support so implementing this would be a big quality of life improvement for Saturn games.

**Comment by Zet-sensei** [comment]
Waiting for the approval of the PR before closing the issue.

**Comment by Zet-sensei** [comment]
Is there something missing for reopening the issue ?

Asking for the account of @rattboi on Discord.

**Comment by srg320** [comment]
> Is there something missing on the PR as we need to reopen the issue ?

For some reason, the issue closed automatically when I accepted the PR. So I reopened the issue)

**Comment by Zet-sensei** [comment]
As I've not received any complaints or new issues since a week about the Shuttle mouse support, I'm closing the issue right now.
