### ISSUE TITLE
Sega Rally Championship 2-player broken

### ISSUE THREAD

**Issue by dfilskov** [MiSTer-devel/Saturn_MiSTer#149]
Two player mode in Sega Rally Championship only shows the background - not the track itself.

1-player mode works fine, though.

Tested on build 20240307_15b8c0

Thanks so much for all your effort!

**Comment by Kuba-J** [comment]
For me the 2 player mode works , but the picture flashes white often during the race 

![IMG_20240311_065001896](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/1526267c-8e2b-4a1a-bf38-3c87c5c25af7)

20240307 + latest unstable main mister

Sdram 2.9

**Comment by dfilskov** [comment]
I think I have the latest unstable MiSTer too (2 days old or so)

I'll check and get back if I can make it work with another MiSTer version.

**Comment by Kuba-J** [comment]
everything should be working ok now , core 20240313 

please retest :)

**Comment by dfilskov** [comment]
Yes! - 2-player works now!

The audio is weird, though - some sounds now keep playing / loops (e.g. the commentator keeps saying 'go ... go ... go ... go...' and a motor sounds is constantly playing at the lowest pitch like a looong bass note) - but apart from that 2-player works :)

**Comment by dfilskov** [comment]
Yes! - 2-player works now!

The audio is weird, though - some sounds now keep playing / loops (e.g. the commentator keeps saying 'go ... go ... go ... go...' and a motor sounds is constantly playing at the lowest pitch like a looong bass note) - but apart from that 2-player works :)
