### ISSUE TITLE
Shining Force III Crashes When Casting Healing Spells During Battle

### ISSUE THREAD

**Issue by METR0lD** [MiSTer-devel/Saturn_MiSTer#15]
During the opening battle of Shining Force III (first scenario), the game crashes every time a healing spell is cast.

**Comment by Kuba-J** [comment]
from my tests:

original Japanese version - no problem casting the healing spell.

English patched version - the game crashes when trying to cast a healing spell.

**Comment by srg320** [comment]
How to reproduce this issue?

**Comment by Kuba-J** [comment]
Unfortunately you have to get to the first fight, it takes about 10min , here the fight from the 31st minute

https://youtu.be/v92G67Hqpso?si=vp-sR0B4bexr8UY0

**Comment by srg320** [comment]
How to get into a fight fast?

**Comment by Kuba-J** [comment]
https://youtu.be/a2Ar3tCHwUc?si=SafPMOUvq2NP4HDQ here is speedrun, it takes about to 10-11min to first battle. 

For dialogues just hold down the button on the pad, unfortunately you have to see it all .... It is not possible to scroll through the dialogues

**Comment by METR0lD** [comment]
Yes, unfortunately there is no way to skip the lengthy cutscene that is right before the first battle. Every time I test it, I just hold a button down on my controller while doing something else for a few minutes on my computer.

**Comment by DeerSteak** [comment]
@srg320 I just discovered this GitHub issue existed, or else I'd have made a save game sooner.

This file is for use with the USA version of Shining Force III, which I used a Redump image that had been compressed to CHD. You should be able to drop this save into /saves/Saturn on your SD card, load the image, then load the game. You will be in the middle of the first battle and it is Grace's turn. Walk her over to any of the other characters in range, press A to bring up the menu, select Magic and press A, then Heal and press A. Pick your character and there will be a cut scene that freezes in a couple seconds. This is as fast as I can get you there without a savestate. Hope this helps. 

[Shining Force III (USA).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14154478/Shining.Force.III.USA.zip)

**Comment by METR0lD** [comment]
With today's update, the game no longer crashes when using the healing spell! 

That said, the random battle crashes still occur. The blaze spell crashed it on me once after today's update, and it crashed once with a normal attack command as well. With these being more random crashes, and not consistent like the healing spell issue, it's difficult to say how to reproduce it consistently.

**Comment by METR0lD** [comment]
Marking this one as completed, since crashing is resolved as far as my testing shows and all audio issues are resolved as well with today's update.

**Comment by METR0lD** [comment]
Reopening this one, since the random crashing issue started happening again after the build that added gouraud shading support. Difficult to reproduce consistently, but it happens often enough that playing through a single battle is likely to produce it by the end.

**Comment by tnibert** [comment]
I think I can consistently reproduce this issue with the blaze spell.  It seems that if you cast blaze as the first attack of the first battle, the graphics will lock up but the sound will continue to loop.

I also observed that if the issue did not occur on the first cast of blaze, the issue was not triggered by blaze for the duration of the battle.  (Would be good to test a bit more for more confidence in that statement.)

I was able to successfully complete the first battle twice.  The first time, I did not cast blaze at all.  The second time, my first attack was from Grace and my second attack was blaze from Masqurin.  After that, blaze did not trigger the issue during the battle.  This included dying and restarting the battle from the church.

I tested this on:
- Scenario 1
- Single SDRAM (version 2.9) setup
- On the core dated 24 March in the main MiSTer distribution from update_all

**Comment by METR0lD** [comment]
It definitely happens outside of spells as well. Just tested it again with today's new core build, and a regular attack crashed it.

**Comment by srg320** [comment]
Please give more information to reproduce this issue. I am not familiar with this game so "blaze spell" and other terms are just words to me.

**Comment by METR0lD** [comment]
Okay, so try this save. It's during the first battle, and it's saved right at the girl with orange hair's turn. You don't need to have her move or anything. Just have her use the "magic" command and then choose the "blaze" spell (it's a fire magic spell). And then she will automatically target the closest enemy. There is a high chance that the game will crash during the attack. _It does not happen every time_, but if you reload the save and try it a few times, the odds that it will crash at least once is _very_ high in my testing.

Just keep in mind that the crashing is not exclusive to this "blaze" spell or this character. This is just one example of it that seems to occur with a high probability. This test was using the USA version of the game on the latest core build from April 6th 2024.

[Shining Force III (USA).sav.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14908724/Shining.Force.III.USA.sav.zip)

**Comment by srg320** [comment]
> Okay, so try this save. It's during the first battle, and it's saved right at the girl with orange hair's turn. You don't need to have her move or anything. Just have her use the "magic" command and then choose the "blaze" spell (it's a fire magic spell). And then she will automatically target the closest enemy. 

Thank you, that's just what I need.

**Comment by Kuba-J** [comment]
should be fixed with today's core 20240409 , https://github.com/MiSTer-devel/Saturn_MiSTer/commit/852854687851cf4ac3d528890c22c2de70714591

**Comment by METR0lD** [comment]
Just tested the first two battles in their entirety without any issues! Shining Force III seems good to go on my end, so I'm closing this one. Thanks again srg320! Amazing work as always!
