### ISSUE TITLE
Ogre Battle - unit's vertical location flickers up and down the map in 3D view mode.

### ISSUE THREAD

**Issue by METR0lD** [MiSTer-devel/Saturn_MiSTer#150]
In Ogre Battle: The March of the Black Queen, when using the 3D map view, all the units on the battlefield have their vertical position flicker up and down the field rapidly when scrolling around the map.

The easiest way to test this is to press the R button to switch to 3D view (2D view is the default), and then hold the Z button down to easily scroll around the map. You can see every unit's position will flicker up and down the field wildly as the map scrolls.

**Comment by METR0lD** [comment]
Been awhile since I provided an update on this one. As of today's build (April 3rd, 2024), this issue is still present.

**Comment by METR0lD** [comment]
Here's an image that shows the issue in action. You can see that unit is completely off the map. But her actual location is on the castle you see on the lower part of the image.

<img width="460" alt="image" src="https://github.com/MiSTer-devel/Saturn_MiSTer/assets/147565839/f9769721-52c9-4412-8c27-edeffd994a92">

**Comment by srg320** [comment]
Can you share a save file?

**Comment by METR0lD** [comment]
I apologize, but I was using the english fan translated version of the game for this. And when I just tested the native japanese version of the game, this issue is not present. So I think the problem is actually with the fan translation, and not an issue with the core itself. I will close this one!
