### ISSUE TITLE
DualSdram core version - doesn't work

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#151]
The latest version of  dualsdram core does not work.

**Comment by Kuba-J** [comment]
No change with today core, 20240315

Will the dualsdram version still be supported ?

**Comment by Kuba-J** [comment]
Hi srg320

I wanted to report that yesterday's dualsdram core (fix for the dualsdram project ) is not working for everyone.

I'm a little confused. For me the core resets the MiSTer. I have no such problems with dualsdram core 20240307.

I checked:

I copied core 20240315 in different ways.
then I copied core 20240307 again - works fine, no problems
I checked some other sdram in the second slot -  versions 2.2 , 2.4 and 2.9
different sd card, mister main unstable 20240313 and last official one, 
I checked on 2 Mister. 

Unfortunately, I ran out of ideas. 

Test test core dualsdram for PSX and Jaguar works without any problems too.

Gretings 

Kuba

**Comment by srg320** [comment]
Check position of switch SW3, it must be on.

**Comment by Kuba-J** [comment]
I have it set up, I've been testing different things for years. I tested core 20240315 on two MiSTers. 

video:

https://www.youtube.com/watch?v=FMrgJ-ryZnI

**Comment by Zet-sensei** [comment]
The dual RAM core 20240315 (fix for the dualsdram project) works for me (and another user on Discord), but not for others.

**Comment by Kuba-J** [comment]
Дякую! I'll check it soon :)

**Comment by Kuba-J** [comment]
the core version you shared with me works perfectly! thank You :)

**Comment by Kuba-J** [comment]
Yes, I also tried this earlier on my own and the core started working properly.

**Comment by srg320** [comment]
Try this build with latest framework changes
[Saturn_DS.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14655228/Saturn_DS.zip)

**Comment by Kuba-J** [comment]
> Try this build with latest framework changes [Saturn_DS.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14655228/Saturn_DS.zip)

this core doesn't work for me

**Comment by srg320** [comment]
Try this one
[Saturn_DS.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14655692/Saturn_DS.zip)

**Comment by Kuba-J** [comment]
sadly , the same result

**Comment by srg320** [comment]
Try this build 
[Saturn_DS_4.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14656487/Saturn_DS_4.zip)

**Comment by Kuba-J** [comment]
> Try this build [Saturn_DS_4.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14656487/Saturn_DS_4.zip)

works fine!

**Comment by srg320** [comment]
> > Try this build [Saturn_DS_4.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14656487/Saturn_DS_4.zip)
> 
> works fine!

Does your Mister setup have IO board installed? What version?

**Comment by Kuba-J** [comment]
I don't have i/o, only de10 nano. 

For core testing with the second MiSTer I removed the i/o , I only checked with de10 + 2x sdram. Same result.

**Comment by srg320** [comment]
Try this build 
[Saturn_DS_5.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14670306/Saturn_DS_5.zip)

**Comment by Kuba-J** [comment]
> Try this build [Saturn_DS_5.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14670306/Saturn_DS_5.zip)

works good :)
