### ISSUE TITLE
Problem with region detection

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#152]
There is some problem with region detection. The games run too fast, the sound too. After selecting the EUROPE region and going back to AUTO or USA/JAPAN settings, the games work correctly again. 

Some games reported on discord: Sakura Taisen, Waku Waku 7, Elevator Action, Magic Knight Rayearth

core 20240313

**Comment by METR0lD** [comment]
To further elaborate, the core starts by running at 63hz, which speeds up everything. That even includes the bios, every game, and also audio. Switching the region to a PAL region (e.g., Europe), flips the speed down to 50hz, and switching it _back_ to an NTSC region (e.g., Japan or USA) corrects the original problem back to the appropriate 60hz.

**Comment by Zet-sensei** [comment]
After some further tests, I tried to recompile the 20240313 version of the core + reverting the recent sys update commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/ab7208ef788337692a372e905c3e547bf8979939 to a previous state.

The core works once again after that.

**Comment by Zet-sensei** [comment]
Maybe a problem with that recent sys update commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/ab7208ef788337692a372e905c3e547bf8979939

**Comment by birdybro** [comment]
I compiled a build that only reverts the recent update to the framework and others confirmed the same thing, that the BIOS screen when region is set to auto detection starts at 63hz.

I suspect some of the pll_cfg changes might be involved?

**Comment by Kuba-J** [comment]
Fixed with today core , 20240315
