### ISSUE TITLE
Sonic Jam: vertical distortion (like bars or slices of the image) on manuals (Japanese ISO)

### ISSUE THREAD

**Issue by FGKey2040** [MiSTer-devel/Saturn_MiSTer#153]
Might be an artifact of how the game handles zooming? Issue is obvious when selecting virtual manuals then confirming on a page to read

**Comment by Kuba-J** [comment]
Please post some pics or video, If these are lines appearing at different times, then many games have it that way

**Comment by Kuba-J** [comment]
ok i see what the issue is! sometimes artifacts appear for a while

**Comment by srg320** [comment]
Can you show a screenshot?

**Comment by YLFAndy** [comment]
![2024031813471112](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/115659432/4f6291f2-a80b-4ebb-9582-a5c428b0ab01)

**Comment by YLFAndy** [comment]
Repro steps:
Launch Sonic Jam
Choose "Game"
Pick a Genesis Sonic game
Choose Options
Choose Manual
Press R or L to flip into the manual
Press A to zoom

Result: There are vertical slices through the image

Expected: No alignment/graphical corruption issues

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone?

**Comment by real-amano** [comment]
@FGKey2040 can you re-test and close the issue if it is gone? According to the changelog it has been fixed many months ago.

**Comment by FGKey2040** [comment]
Issue appears resolved
