### ISSUE TITLE
Bust-A-Move 2 - Arcade Edition (USA) // Some backgrounds stages aren't correctly rendered (green line)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#155]
During some battles against the CPU opponent, some backgrounds aren't correctly rendered as a green line appears on the bottom of the playflied.
![Bust](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/52127625/516b9802-662d-4bcf-8ec1-1c6cc7a3c5c9)

**Comment by srg320** [comment]
The green line is present on the original hardware. 
![_storage_emulated_0_DCIM_Camera_IMG_20240317_211027](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/40274294/50b03d95-e1c7-47d7-bc95-3bead4567672)

What other glitches?

**Comment by Zet-sensei** [comment]
No other visual issues found, it was this green line that I took for a bug on the core.
Present on the original game & hardware.

Thanks for checking.
