### ISSUE TITLE
Virtual On Screen Corruption during replays 

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#156]
Virtual On Screen Corruption during playback of saved replays.  This is on the unstable build from 3-15-24

**Comment by srg320** [comment]
How to reproduce this issue?

**Comment by gleek12** [comment]
To save a replay, press L and R during a replay at the end of a match.  It will have you the option to save the replay to the internal memory.  Then play it back using the “replay” option in the main menu.

**Comment by RGarciaLago** [comment]
Attached a save with a replay on the Green Hills stage that has the vertical cloud issue. You'll have to rename the extension from ".dmp" to ".sav"
[Virtual On - Cyber Troopers (USA).dmp](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14643359/Virtual.On.-.Cyber.Troopers.USA.dmp)

**Comment by gleek12** [comment]
This bug appears to be fixed in the latest release!  Thank you!
