### ISSUE TITLE
Virtual On - Green Hills clouds scroll vertically 

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#157]
During the green hills stage, the cloud background layer continuously scrolls vertically, regardless of what the camera is doing.  On real hardware, this would not be happening.  Tested on the unstable build from 3-15-24

**Comment by srg320** [comment]
How to get to the Green Hills stage quickly?

**Comment by gleek12** [comment]
I think green hills is the 4th stage.  The only shortcut I can think of is to set matches to be only one round. And I think you can lower the difficultly.  Perhaps once you get there you can save a replay so you can just run the replay from the main menu for testing.  Replays play back corrupted so maybe it will help with troubleshooting that bug as well.

**Comment by YLFAndy** [comment]
[virtualongreenhillbug.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14642610/virtualongreenhillbug.zip)
Here's a video of the issue. Looking at the top of the screen, it's clear the clouds are moving vertically instead of horizontally. Hope that helps!

**Comment by gleek12** [comment]
This video shows what it should look like on actual hardware

**Comment by RGarciaLago** [comment]
Attached a save with a replay on the Green Hills stage that has the vertical cloud issue. You'll have to rename the extension from ".dmp" to ".sav"
[Virtual On - Cyber Troopers (USA).dmp](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14643320/Virtual.On.-.Cyber.Troopers.USA.dmp)

**Comment by srg320** [comment]
Here's what it looks like on my original hardware.
https://youtu.be/E-Kc321rqYY

**Comment by gleek12** [comment]
Wow, maybe it’s just a bug with the original game, then.  If it’s happening on original hardware too, then I guess it’s not a bug with the core after all.  I will close this ticket.  Apologies!

**Comment by gleek12** [comment]
Ok, I figured out the confusion.  The cloud bug is present in the standard US release of VO, but the net link edition has the bug fixed.  The core appears to be accurately displaying the cloud background in both relesases.

**Comment by YLFAndy** [comment]
> Ok, I figured out the confusion. The cloud bug is present in the standard US release of VO, but the net link edition has the bug fixed. The core appears to be accurately displaying the cloud background in both relesases.

Cool find! Glad it's not the core...
