### ISSUE TITLE
Grandia - polygon tearing

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#158]
Grandia environments tend to exhibit polygon seams and tearing that were not present on original hardware.  A good example would be on Marna road (the first area outside of town).  If you run along the river you should start to see the ground start to show seams and tearing.  Tested on the unstable build from 3-15-24

**Comment by Kuba-J** [comment]
the same thing occurs in many games
Croc:

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/5397279a-e921-42e3-a50c-38e05cca346d



Vandal Hearts:
![VANDAL](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/2d7b653e-4cce-4ec2-a0ca-d431b4d20696)

Virtual Hydlide:
![VIRTUAL](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/9283a69c-c312-45bc-b279-05462b3779ea)

**Comment by real-amano** [comment]
@gleek12 can you close that issue?

**Comment by gleek12** [comment]
Closing!  Thank you!
