### ISSUE TITLE
Asuka 120% Limited - Burning Fest. Limited // Sound Randomly Cuts Out

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#16]
Asuka 120% Limited - Burning Fest. Limited has an issue with rendering shadows. The game normally takes the original sprite of the playable characters and mirrors, squashes, and blackens it with dithering and flashing to simulate shadows. But the core as of the official October 10th 2023 build fails to black out the sprite, so it causes all shadows to be just the characters mirrored and squashed.

![20231010_221459](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/e5d6e218-2695-471a-ae3d-9bdcceab458f)

There is also an issue of the sound effects randomly cutting out in general.

On a side note, the unofficial updated version Asuka 120% Limited Over has the same problems, since it recycles the same engine and assets.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-02-06 14-07-33](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/b23952aa-e967-4a4d-8a0f-b9412bb90cf3)
Looks like the February 6th 2024 fixed the shadows, but the inconsistent sound is still an issue.

**Comment by Zet-sensei** [comment]
With a recent commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f0aa89a9d7e4be232a237c053d9aa438bff9b5fe on the SCSP, the issue will probably need to be reevaluated.

On my tests on the menus and 3/4 battles with core 20240229, I didn't detected missing sound effects anymore.
But I need a second evaluation on it - just to be sure that I've not missed something. 
Thanks.

**Comment by real-amano** [comment]
@InfernoHabanero , can you close the issue?

**Comment by real-amano** [comment]
@InfernoHabanero , can you test, if it is fixed, and  close the issue?
