### ISSUE TITLE
Bug! - Crystal Sound Effect not accurate

### ISSUE THREAD

**Issue by vmicka72** [MiSTer-devel/Saturn_MiSTer#162]
When taking a crystal in first level sound is different from real hardware.

**Comment by vmicka72** [comment]
Tested with 20240409 core. Seems to be fixed in one of previous release.

**Comment by vmicka72** [comment]
After comparing with Real hardware sound is different.

**Comment by real-amano** [comment]
@vmicka72 is this fixed with the latest revision?

**Comment by real-amano** [comment]
@vanfanel found that this is not fixed entirely:

[Quote] With regard to VGE's video: his videos are always rushed (he makes money by following Youtube's algorithm with non-stopping and repetitive talking, often half informed) and he even shows "Bug!" as a game with perfect audio while at least one sound effect is broken on the same video, look at exactly 10:03:

https://youtu.be/5cUp3U4Y4kM?t=603[/quote]

**Comment by real-amano** [comment]
@vmicka72 , is this fixed now?

**Comment by vmicka72** [comment]
I'm in holidays. I will test it after 16 August 😉

**Comment by vmicka72** [comment]
I just test it with last release (20211010). The sound is worst than april version. The SCSP need some work :-)

**Comment by vanfanel** [comment]
> I just test it with last release (20211010). The sound is worst than april version. The SCSP need some work :-)

You should test latest code instead.
Sound has improved immensely.

**Comment by vmicka72** [comment]
20241010 is not the last version (i wrote 20211010 but i test it on 20241010)?

**Comment by vanfanel** [comment]
> 20240810 is not the last version (i wrote 20211010 but i tested it on 20240810)?

Yes, thats the last build. 
Sound has improved for sure. Have you compared Bug! in the core VS real hardware?

**Comment by vmicka72** [comment]
> > 20240810 is not the last version (i wrote 20211010 but i tested it on 20240810)?
> 
> Yes, thats the last build. 
> Sound has improved for sure. Have you compared Bug! in the core VS real hardware?

Yes i follow progress and i tested it because sound improvments was made but the sound is  worst than previously. I compared it with Real hardware. I think this is normal because Sergei is working on scsp actually.

**Comment by vmicka72** [comment]
Fixed in 20240817 release.

**Comment by vmicka72** [comment]
Fixed in 20240817 release.

**Comment by vanfanel** [comment]
Great!!
