### ISSUE TITLE
Nights Into Dreams (USA) audio issue

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#163]
Core 20240318

Sound glitch occurs during character selection

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/b82eb2ac-8038-47de-b18f-c4ee8855f676

**Comment by Zet-sensei** [comment]
Can't reproduce on my side.

**Comment by Kuba-J** [comment]
It turned out that the image of the game that I have has been patched, 

the new image of the game works ok , sorry !
