### ISSUE TITLE
Sega Rally (USA) Title screen issue / regression

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#167]
On the title screen, there is a graphic error on the left side , bar , core 20240322

![IMG_20240322_185053847](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/ce5fb8b3-fc70-490d-97cf-a9e7e16a00a5)

**Comment by METR0lD** [comment]
I can confirm that it also appears on the screens that appear between each track during the rally.

<img width="495" alt="image" src="https://github.com/MiSTer-devel/Saturn_MiSTer/assets/147565839/1969a5a8-90d8-4ea0-bc5f-1bf995d99c9e">

**Comment by Kuba-J** [comment]
Same for Thunder Force in game, stage 2

![IMG_20240322_193456265](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/a14952fc-a0c7-4090-ac1d-69d6b7a224af)
![IMG_20240322_193502272](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/78c06008-6c94-442a-b518-b8f7656e9d21)

**Comment by real-amano** [comment]
I guess that this is the VDP1 regression that is mentioned in the current changelog. Hopefully fixed now.

**Comment by Kuba-J** [comment]
Fixed , core 20240323
