### ISSUE TITLE
SEGA Saturn Core Has A Blank Vertical Line On The Right Of The Screen

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#168]
![Untitled](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/b515a892-d4f3-49ea-a6e3-9f6528b474ac)
![Untitled2](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/c5318632-1447-4690-8828-a5e5826e9877)

So I was playing around with the SEGA Saturn core trying to get a 4:3 aspect ratio, and I noticed that there was blank space on the right of the screen. At first I assumed it was some quirk with the SEGA Saturn hardware I wasn't aware of, but I knew something wasn't right because no other core gave me this specific issue.

So I decided to test it out by using a raw screenshot from an emulator and the SEGA Saturn core outputting at an integer scale, both images scaled to 1280x896 for better visibility. As you can see, despite technically being the exact same resolution, the SEGA Saturn core is not showing the entire image. One vertical line on the right is not being shown like it should, which then creates four blank vertical lines when scaled up four times.

![Untitled3](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/06aaa598-1dd7-4fa1-bd25-f61739cbfba1)
![Untitled4](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/11cc9ede-b420-4354-ab02-802990c1279f)
 
Interlaced content is also producing a similar problem, for example on the title screen for Virtua Fighter 2 there are two vertical lines on the right of the screen from the SEGA Saturn core being blanked out when scaled two times to 1408x896.

**Comment by real-amano** [comment]
I wonder if this is the same issue as #22

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/4f9777657f0a23603d1b3d3561dab0a25d4a30ef

**Comment by real-amano** [comment]
@InfernoHabanero probably another one bit the dust ;)
