### ISSUE TITLE
Pandemonium/Magical Hoppers // Game Runs At Half Speed

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#17]
Pandemonium (NTSC-U) and Magical Hoppers (NTSC-J) both run slower than they should, at about half the speed. The FMV cutscenes aren't affected, suggesting it's related to how the core is rendering the graphics that is creating a bottleneck.

This issue has been the case as of the official October 10th 2023 build.

**Comment by real-amano** [comment]
Issue #96 has a video that shows the slowdown.

**Comment by real-amano** [comment]
@InfernoHabanero Did the fix today help only Pandemonium or Magical Hoppers as well?

**Comment by InfernoHabanero** [comment]
> @InfernoHabanero Did the fix today help Pandemonium/Magical Hoppers?

Yeah the new unstable build significantly sped up both games, now being on par with the original hardware. So I'm closing this issue for now.
