### ISSUE TITLE
[FEATURE REQUEST] 480i Analog Video support. 

### ISSUE THREAD

**Issue by JaeOfMordor** [MiSTer-devel/Saturn_MiSTer#170]
currently all analog video output is displayed as 240p, any 480i is displayed as 240p with a deinterlacing effect.

**Comment by Zet-sensei** [comment]
An attempt is done here - https://github.com/MiSTer-devel/Saturn_MiSTer/pull/258

**Comment by JaeOfMordor** [comment]
fr fr. closing now
