### ISSUE TITLE
 Bubble Symphony ~ Crackling Sound  & pixel problem

### ISSUE THREAD

**Issue by neosquid** [MiSTer-devel/Saturn_MiSTer#171]
In Bubble Symphony, each time the player jumps, a slight hiss/crackle can be heard.

There also seems to be a problem with the first top left pixel, which seems to be drawn incorrectly, while in game.

**Comment by real-amano** [comment]
@neosquid Is this fixed by the recent commits?

**Comment by neosquid** [comment]
The sound problem is fixed, the pixel issue still exists.

**Comment by real-amano** [comment]
Is the pixel error a thing on the real Saturn hardware? It might be hidden in the overscan area there?

**Comment by Kuba-J** [comment]
I also see brighter pixel in some games 

Bubble Symphony
![IMG_20240329_201125861](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/71a7a48e-9ee0-41ba-9c01-ffbfeb731ab0)

Rayman
![IMG_20240329_201027998](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/bab3c9a0-51c6-47e0-bb3c-be6d5b5cbaf1)

**Comment by neosquid** [comment]
> Which pixel exactly? ![20240329_180305-screen](https://private-user-images.githubusercontent.com/40274294/318111543-e5c12f1a-13bf-4f17-8693-cc1133098f96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzMwNjEsIm5iZiI6MTcxMTkzMjc2MSwicGF0aCI6Ii80MDI3NDI5NC8zMTgxMTE1NDMtZTVjMTJmMWEtMTNiZi00ZjE3LTg2OTMtY2MxMTMzMDk4Zjk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAwNTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYjNhODQ3MDBjNzgxZDlmMDExYzRjMjg1ZGE0MWJjOTA3OGRmNTBmMWI3MDA1OGZjNTczOWYxYzdjMmNiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GdIBDTN6sr0vFhHFHLcpDSJp1pfSs7truQZkac9l264)

The same pixel shown by Kuba-J's screenshots.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/bd90d3afce6b150526f737e3229758f4c576a2b0
