### ISSUE TITLE
P2 replicates some P1 inputs

### ISSUE THREAD

**Issue by RGarciaLago** [MiSTer-devel/Saturn_MiSTer#174]
On the latest unstable core (**Saturn_DualSDRAM** unstable build: https://github.com/MiSTer-unstable-nightlies/Saturn_MiSTer/releases/download/unstable-builds/Saturn_DualSDRAM_unstable_20240329_1242b1.rbf) Player 2 works and automatically replicates the Start + A/B/C button inputs from Player 1. This with “Pad 2” and “SNAC” set to off in the core input options.

**Comment by Kuba-J** [comment]
Fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/89a7639034ae858c4b0efa361eaabb01047a7961

**Comment by real-amano** [comment]
@RGarciaLago Can you confirm it is fixed and close the bug?

**Comment by RGarciaLago** [comment]
@Kuba-J * @real-amano thank you very much! I tested the latest build and it’s fixed!

**Comment by RGarciaLago** [comment]
@Kuba-J * @real-amano thank you very much! I tested the latest build and it’s fixed!
