### ISSUE TITLE
Rayman (USA) // REGRESSION - Freezes after selecting or creating a save file

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#175]
Rayman is known to be quite sensible with pad timings (SCU) on the system.

Most maybe that commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f5848a1f1d94662627ebdc245b2ebd8f92062379 introduced a regression with that game.

**Comment by Kuba-J** [comment]
Fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/89a7639034ae858c4b0efa361eaabb01047a7961
