### ISSUE TITLE
Interlaced screen mode is outputting 15KHz for linedoubled analog out (VGA) instead of 31KHz

### ISSUE THREAD

**Issue by vermian** [MiSTer-devel/Saturn_MiSTer#176]
I'm using a PC CRT monitor using analog VGA out from my MiSTer with linedoubling enabled for 480p/31KHz.
Normally, 240p/15KHz is linedoubled to 480p/31KHz, but with Saturn games that use the interlaced/high-res mode, only 15KHz is output which my VGA monitor (and most others) does not support. 
For example, the menu of "Bulk Slash" is interlaced high-res and causes this issue. Also noticed the same with the Panzer Dragoon 2 menu and the Panzer Dragoon Saga menu. Once you get past the menu of these games, it goes back to linedoubling 240p -> 480p properly.

**Comment by real-amano** [comment]
I guess that the feature request #170 is probably related if not the same.

**Comment by vermian** [comment]
> I guess that the feature request #170 is probably related if not the same.

That looks like a different issue. His CRT is probably 15KHz, which means he is not using the linedoubling like I am for a 31KHz PC CRT monitor.

**Comment by JaeOfMordor** [comment]
@vermian might want to test again with the latest version that just dropped

**Comment by JaeOfMordor** [comment]
15 kHz video output is now  fixed

**Comment by tehgan** [comment]
Still running into this issue on the latest build (20241030_14f3a8.rbf) with Sonic Jam. Sonic World and the games themselves work fine, but the menus don't output any signal to my monitor, and I'm assuming it's because they're interlaced/15khz.

I'm running my MiSTer through a digital IO board with an HDMI->VGA adapter, and I have 'direct_video=1' and 'forced_scandoubler=1' set in MiSTer.ini.

**Comment by JaeOfMordor** [comment]
@tehgan this is a newly introduced regression already logged with issue #263 .
what this guy  asked for 31 kHz interlaced support, is implemented. and the issue can be closed.

there’s a lot of abandoned issue tabs that need clearing

**Comment by real-amano** [comment]
@vermian With linedoubling removed from the core now I guess that your issue is now obsolete?

**Comment by vermian** [comment]
> @vermian With linedoubling removed from the core now I guess that your issue is now obsolete?

Not sure what build I'm supposed to use for testing. I saw some builds floating on the discord but posted with no context. Is there any instructions or just try one of those?

**Comment by real-amano** [comment]
Latest **Saturn** unstable build: https://github.com/MiSTer-unstable-nightlies/Saturn_MiSTer/releases/download/unstable-builds/Saturn_unstable_20241201_17e3c0.rbf
```[Sergiy Dvodnenko 2024-12-01 e3c04ec] Update README.md```

**Comment by thesunnymachine** [comment]
> Latest **Saturn** unstable build: https://github.com/MiSTer-unstable-nightlies/Saturn_MiSTer/releases/download/unstable-builds/Saturn_unstable_20241201_17e3c0.rbf `[Sergiy Dvodnenko 2024-12-01 e3c04ec] Update README.md`

This build and the new one Saturn_unstable_20241202_195ef3.rbf  Do not output interlaced over analog out for me.  Other cores are confirmed working, this fix for interlaced output doesn't work for me.

**Comment by real-amano** [comment]
This is not a fix. Linedoubling was removed altogether. Thus I said your issue is obsolete, not fixed.

**Comment by vermian** [comment]
Did srg320 mention he will not be doing linedoubling on the core? Let me know where to find that info.

**Comment by real-amano** [comment]
There is a bug for unclutter the menu by removing settings for features that don't work. And linedoubling doesn't work for 480i content and was removed for N64, PSX and now for Saturn.

**Comment by Kuba-J** [comment]
scandoubler is impossible to do , it does not work with 480i , there were attempts unfortunately failed.

**Comment by real-amano** [comment]
I am not really sure what you are questioning here? 
He himself removed it: https://github.com/MiSTer-devel/Saturn_MiSTer/commit/195e78dda737f75f15e9a22f95115e8ccb069dcc
He himself and probably in his right set of mind called it a useless option.

**Comment by vermian** [comment]
I just needed a link or screenshot to what he said. I don't consider it useless but it's his core so I'll be closing this issue.
