### ISSUE TITLE
World Series Baseball 98 (USA) - game won't boot

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#178]
After the Sega logo , it briefly shows the wording in the lower right corner "Loading" flashes a few times and is left with a black screen.
https://youtu.be/3OjPUo4Up98

tested on  latest core 20240403

**Comment by srg320** [comment]
This games have the same boot code and the same issue:
Pro Yakyū Greatest Nine 97
Pro Yakyū Greatest Nine 97 Make Miracle
Pro Yakyū Greatest Nine 98
Pro Yakyū Greatest Nine 98 Summer Action

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/c0b461012e548d59ef6d6cf1f61b22a3ca5ee989 , core 20240420

**Comment by Zet-sensei** [comment]
The game boots now, but have issues later before entering into the main game.
You can navigate through the menus, select your teams and very detail for your gameplay.
But it remains on a black screen with background music instead of loading & accessing to the main game.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1558f7ead60a293b44e7c2c9d5d1510fd811d44c
