### ISSUE TITLE
Discworld 2: Controller disconnects (SNAC and HPS)

### ISSUE THREAD

**Issue by YLFAndy** [MiSTer-devel/Saturn_MiSTer#179]
Description:
When playing Discworld 2, the game will randomly throw up a 'GAME PAUSED No Controller Detected Please connect a Controller' <sic> error message. The controller still controls the cursor without issue but you have to click the check box every time, making the game unplayable. 
This happens over SNAC or emulated controller (this has been happening for as long as Discworld has booted. The latest update made it slightly better, but it's still pretty constant, whether you move the controller or not).

Possibly a polling issue. Verified on real NTSC hardware using the PAL game and the issue does not reproduce. 

Repro Steps:
In the latest core, launch Discworld II (EU)
Verify Controller 1 is enabled and controller 2 is disabled in the core settings (this doesn't matter, it reproes either way, but just to eliminate variables)
Press the start button to skip cutscenes until you get control of the cursor at the front of the castle

Result:
The error message will pop up frequently, but somewhat randomly. 

Expected:
No error

![2024040414550100](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/115659432/a614e58d-a1f0-4017-9d6d-6d91c3065620)

**Comment by Kuba-J** [comment]
should be fixed with today core https://github.com/MiSTer-devel/Saturn_MiSTer/commit/61c8a8577b07d2557b1b83d374f6edf735f213e6 , please retest

**Comment by YLFAndy** [comment]
Tested and closing as fixed.
