### ISSUE TITLE
Shin Shinobiden /Shinobi Legions freezing before title screen

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/Saturn_MiSTer#18]
## Expected Behavior
The game should not freeze after intro

## Current Behavior
Shin Shinobiden freezes after pressing start during intro
Shinobi Legion, which is the US version boots into black screen

## Steps to Reproduce

1. Launch Shin Shinobiden
2. Press start during intro

## Context (Environment)
Single SDRAM
Latest official build of the core

**Comment by allen77710** [comment]
> I just read that this is a game bug and not a core bug (thanks Kuba for pointing that out). https://segaretro.org/Shinobi_Legions
> 
> I will close this ticket

Isn't this a game bug? This game works fine on real Saturn hardware, emulators, and any ODE
