### ISSUE TITLE
Albert Odyssey - Graphics Glitches

### ISSUE THREAD

**Issue by cerulean-hero** [MiSTer-devel/Saturn_MiSTer#182]
Misc. graphics glitches appear all over the screen in the town of Bugdoniel while walking in Albert Odyssey: Legend of Eldean. Save file attached. When the save file loads, just walk around and the issue will appear.

Build: Saturn_unstable_20240406_15769c (Single RAM)
BIOS: Bios Saturn 1.01a (U)
[Albert Odyssey - Legend of Eldean (USA).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14899361/Albert.Odyssey.-.Legend.of.Eldean.USA.zip)

**Comment by srg320** [comment]
Please show a screenshot or video of the issue. 
So far I only see the sandstorm effect.
