### ISSUE TITLE
Sky Target (USA) freezes during intro cinematic

### ISSUE THREAD

**Issue by RGarciaLago** [MiSTer-devel/Saturn_MiSTer#183]
Sky Target consistently freezes during the intro cinematic. Repro rate was 5/5 for me and I also confirmed with other users that it occurs for them.

I am using CHD but another user reported that bin/cue works fine.

**Comment by Kuba-J** [comment]
works ok after starting , but on the third playback it also crashed fmv (bin/cue )

**Comment by real-amano** [comment]
Should be fixed with the current core updates.

**Comment by RGarciaLago** [comment]
@real-amano thanks for the reminder! Just checked and it's indeed working. Left the game running for ~15 minutes and it went through the entire intro video three times without issue. Closing bug!
