### ISSUE TITLE
Battle Garegga - Sprite Rendering Issues when Selecting Specific Screenmode Option

### ISSUE THREAD

**Issue by EzDzzIt** [MiSTer-devel/Saturn_MiSTer#184]
In-game in BG, after selecting the 'screenmode' option setting seen in the attached image, certain sprites don't get drawn correctly during gameplay (for example, medals and bullets- example of a medal sprite in this mode attached).

All other screenmode options seem to be working fine, only this "zoomed-out" screenmode breaks sprites as far as I can tell. A couple users confirmed similar behavior after selecting this screenmode.

![IMG_2526](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/143894375/73ba27db-0085-4a6a-860f-2f85f1b33a18)
![IMG_2527](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/143894375/21d8d9d5-0fa5-4a2e-be8f-4e941927f1aa)

**Comment by real-amano** [comment]
@EzDzzIt Should be fixed by the updates today. Please test again and close the issue if you agree.

**Comment by EzDzzIt** [comment]
Confirmed fixed in 4-17 unstable build
