### ISSUE TITLE
Resident Evil NTSC/US version: Status/inventory screen is not rendering except text in lower left

### ISSUE THREAD

**Issue by Isles487** [MiSTer-devel/Saturn_MiSTer#185]
This is a regression introduced in unstable build 20240406_15769c. Build 20240403_13e38a was the last build without the issue. If the player presses "start" to bring up the inventory screen, the screen is black with the exception of item name in the lower left of the screen.

Tested against both single ram and dual ram versions.

**Comment by Isles487** [comment]
[Resident Evil (USA).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14939144/Resident.Evil.USA.zip)

Adding save file for ease of testing.

**Comment by Zet-sensei** [comment]
Seems to be fine now when I tested today on core 2024-04-17.

Please retest and update the issue, thanks.

**Comment by Isles487** [comment]
Fixed in unstable build 20240417, both dual ram and single ram.
