### ISSUE TITLE
Revolution X - Music Is the Weapon // REGRESSION - Black screen after BIOS logo

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#188]
After some extensive tests, "Revolution X - Music Is the Weapon" isn't launching anymore.

The German, Europe and USA versions of the game can't go in-game anymore and stay on a black screen after the BIOS.

I've tested with the Auto setting +trying to force the region with all BIOS (Europe, USA, JP, Hi-Saturn, V-Saturn) on 3 versions impacted. 
No changes at all.

Only the Japan version of the game could work with all BIOS versions (with either Auto or 'Japan' forced region setting).

**Comment by Zet-sensei** [comment]
Confirmed with another user on Discord, with the Europe BIOS/Europe version of the game.
Same issue.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/c0b461012e548d59ef6d6cf1f61b22a3ca5ee989

**Comment by Zet-sensei** [comment]
Andy D. on Discord have seen something with core 2024-04-20.

"The game is still not booting [...] if SNAC is enabled. Disabled, it boots fine."

**Comment by YLFAndy** [comment]
After more testing: The 3D pad MUST be in digital mode on real hardware or the game will not boot. On the core, however, the game will not boot if a 3D pad is connected with SNAC regardless of whether or not it's in Digital mode. Which is related to https://github.com/MiSTer-devel/Saturn_MiSTer/issues/192
