### ISSUE TITLE
New issue: Saturn BIOS cannot skip (but the stable release (20240328 could)

### ISSUE THREAD

**Issue by mhmetalheart** [MiSTer-devel/Saturn_MiSTer#189]
Last 2 updates couldn't skip the bios logo. include: press A or B or C or Start won't skip. 
Hold L or R to reset won't force to BIOS. 
stable 20240328 can do like real console.

**Comment by Kuba-J** [comment]
No issues here , works fine

**Comment by Zet-sensei** [comment]
Can't reproduce it too.

**Comment by mhmetalheart** [comment]
strange. I will test again today. thanks for reply.

**Comment by mhmetalheart** [comment]
resolved, answer is: BIOS 1.01 J this time stuck. I change to HI and V, all OK.
Please resolve the bios issue. thanks.

**Comment by Kuba-J** [comment]
I use jp 1.01 works fine, please resolve your setup issue.

**Comment by Kuba-J** [comment]
https://youtu.be/Gvyg_I5SVMY?feature=shared

**Comment by mhmetalheart** [comment]
Now that make me very confused. No reason the HI and V, even 1.00 works fine, but just only the 1.01J stuck. I will see what happened at my side again. I will close this issue now.
