### ISSUE TITLE
MK2 crashes when performing a fatality on US version. 

### ISSUE THREAD

**Issue by Gouki94** [MiSTer-devel/Saturn_MiSTer#19]
Tested with Scorpion on pit stage. US Romset

**Comment by Fonsie001** [comment]
Hello, tried it on the dual ram version 20240212_18e57f the issue still exists, mostly with pit fatalities but also regular fatalities but that happens less

**Comment by srg320** [comment]
How to reproduce this issue? How to make fatalities?

**Comment by Fonsie001** [comment]
Issue is resolved in later versions of the core, tested it on Saturn_DualSDRAM_unstable_20240628_13e17d.rbf and this issue did not occur

**Comment by real-amano** [comment]
@Gouki94 , can you test it again and close the issue?

**Comment by real-amano** [comment]
@Gouki94 , can you test it again and close the issue?

**Comment by real-amano** [comment]
@Gouki94 , since this issue seems to be fixed since at least July can you test the game again and close the issue?

**Comment by Gouki94** [comment]
Issue resolved in latest build, please close

**Comment by Kuba-J** [comment]
> Issue resolved in latest build, please close

I think you can close this case :) 

![image](https://github.com/user-attachments/assets/2c8ef92f-6c00-4125-afea-71d8d7ed67c5)
