### ISSUE TITLE
[Die Hard Arcade] Cutscene taking a minute to load when it used to be instantaneous

### ISSUE THREAD

**Issue by TarkovskysMirror** [MiSTer-devel/Saturn_MiSTer#191]
At the end of the first stage, just after you step into the elevator, the game plays a cutscene that's supposed to load instantaneously. Now it takes at about a minute, or at least long enough for me to think it was frozen at first. I have beaten this game on previous iterations of the core with no problem, though that was a few months ago. Resetting the game doesn't fix the issue.

**Comment by Kuba-J** [comment]
which core version ? stable release or latest unstable?

**Comment by TarkovskysMirror** [comment]
Latest unstable, and also the one before that. Glitch happened in both. And I'm using latest unstable mister main because I was told I needed it to run unstable cores.

I haven't played Die Hard Arcade in a while, and I don't remember which core I used or if I even started using unstable cores when I beat the game. I can go back and test each core to find when the regression happened, if that would be helpful. I'm just busy and can't do it right now. Maybe this weekend I'll have more time.

**Comment by Kuba-J** [comment]
I confirm , the time to load cutscene is more than 1 min. 

Here is video:
https://youtu.be/rxHPNySs0Q0

The latest dualsdram and single core 20240417, bin/cue and unstable mister main 03/31/2024

**Comment by TarkovskysMirror** [comment]
I have one stick of 2.9V ram so I'm using the latest Saturn unstable build, but everything else is the same as your setup, Kuba-J.

**Comment by Kuba-J** [comment]
Thank you for the confirmation. There is definitely something wrong , the cutscene should load quickly.

**Comment by TarkovskysMirror** [comment]
Not a problem. Let me know if there's anything at all I can do to continue helping.

**Comment by Jacky412** [comment]
Hi I can confirm this as well on the latest unstable build. I am using direct video via HDMI to retrotink 4k upscalar. I do not recall having this issue previously without direct video on not sure if there is anything to do with it.

**Comment by real-amano** [comment]
Still an issue?

**Comment by Kuba-J** [comment]
Yes , no change

**Comment by srg320** [comment]
Most likely the issue is in the Main module. I haven't gotten to it yet.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Main_MiSTer/commit/5e23bfe6f314590391cfac88b0cdeea32ceb9147 on Main MiSTer file.

**Comment by TarkovskysMirror** [comment]
Confirmed fixed as of 10/30
