### ISSUE TITLE
Tenchi Muyou! Rensa Hitsuyou (Japan) // Incorrect zoom effect

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#194]
Reported  by a user on Discord.

_"Start a new game and there’s a camera zoom that looks distorted."_

**Comment by Zet-sensei** [comment]
Steps to reproduce the issue

- Press START on the title screen
- Choose the first option

You will see the zooming effect being corrupted.

**Comment by srg320** [comment]
This is a known issue, also listed in the readme. Glitches display a layer on top of a layer that is zoomed. This layer should be transparent. The problem is that the game code applies illegal settings for VDP2.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/55c8d1825324ae67b1c103638fceca95374579c6
