### ISSUE TITLE
REGRESSION - Sega Rally JP/USA - Texture flickering

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#195]
Starting from core 20240417 ( change for vram) you can see more flicker in Sega Rally. This can be seen during the race , but the easiest way to notice it is after the race is over , flashing car textures.

core 20240417 

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/a4681f92-ae8b-4478-86b7-6a56495197e9

core 20240409

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/6419715a-70b6-440a-a630-151591b2b6ba

stable core 20240323

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/f29f68f7-4efb-4cb7-961e-d84ff6828493

**Comment by JaeOfMordor** [comment]
seems to affect multiple games

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/c89bfa2b-c26e-4371-b99c-88071fecf08f

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/674a2e522eacbb54335693395b314484ff20b963 , core 20240504 

thank You!
