### ISSUE TITLE
Machi (Japan) / Music volume pops back up on fade out

### ISSUE THREAD

**Issue by Left-Empty** [MiSTer-devel/Saturn_MiSTer#197]
Hello,

In Machi, the volume of a music track pops back for a split second on fades out, as if it was going back to full volume on reaching the bottom value.
This can be heard very simply right away by just starting the game, pressing start and the C button a couple of times to select Ushio Masami's story (he's the default selected guy). The menu music will do the glitch.
I don't think I have run into another game that does it, or maybe I was just too absorbed.

The glitch happens even with the DSP disabled.

Cheers!

**Comment by srg320** [comment]
@Left-Empty, please specify where exactly does the glitch occur? How often?

**Comment by Left-Empty** [comment]
Hello Sergey, thank you for looking at it!

Here is a video of it in demonstration at the simplest and most reproducible point: the fade out bug happens every time on the game's character selection screen.

https://github.com/user-attachments/assets/e84cabb2-0a76-46bb-ad29-5c6a8b52dc31



You can hear the single little chord pop at around the 17 second mark after the fadeout.

Within the game itself, occurences seem totally random. I have played a couple hours and experience it only two times within the game itself, and the volume pop up sounded much lower than on the character select screen. When I tried to replay those segments to put them on video, the glitch did not happen again, grumble!

I hope everything is going well for you, cheers!

**Comment by real-amano** [comment]
@Left-Empty , is this fixed with the latest revision?

**Comment by Left-Empty** [comment]
It seems to be indeed. Thank you, Sergiy!
