### ISSUE TITLE
PANZER DRAGOON II ZWEI - NO SKY TEXTURE IN 2ND STAGE

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#198]
core 20240423 , Sky texture missing in second level
![IMG_20240429_190701218_HDR](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/f3c7d0be-0eb2-4a13-98f3-67aaf111b77a)

saturn:

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/47639df0-7e90-49de-b3b0-9506c6059a4a)

unfortunately I do not know a way to quickly select level 2 , I have not found anything

**Comment by srg320** [comment]
> unfortunately I do not know a way to quickly select level 2 , I have not found anything

Save?

**Comment by Zet-sensei** [comment]
I'm uploading a Panzer Dragoon Saga save file imported to Panzer Dragoon II Zwei.

So, you can go to : Options > Pandra's Box > Activated it > Select EPISODE > 2nd

[Panzer Dragoon II Zwei (USA).zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/15160668/Panzer.Dragoon.II.Zwei.USA.zip)

**Comment by Kuba-J** [comment]
To clarify, you have to choose the left path in episode 2, which will lead to the moment of the section with flying. The beginning of the stage as well as the right path is ok.

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/55c8d1825324ae67b1c103638fceca95374579c6, core 20240504

thank You!
