### ISSUE TITLE
Densetsu no Ogre Battle // Fails To Load Pass Title Menu

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#20]
Densetsu no Ogre Battle is currently not playable as of the official October 10th 2023 build. The logo and title screen do function as normal, but trying to load into the game cause it to lock on a blank screen.

**Comment by Zet-sensei** [comment]
Seems to be fixed on core 20240110 with my tests.

Please retest on your side and see if the issue should be closed or if we need to update the report.
Thanks.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-01-10 18-49-24](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/62c5971d-dfe9-47f5-b29a-e27ee4e0061d)
![Screenshot 2024-01-10 18-51-52](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/447fbfd1-e98f-4a31-818e-a95f48f8cb91)
![Screenshot 2024-01-10 18-48-05](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/17fe10d2-9bef-404e-8e7d-70f7588323be)

Seems to be working on my end, so I think I'll close this for now.
