### ISSUE TITLE
F1 Challenge (USA) texture flickering 

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#200]
Texture flickering occurs on the Montecarlo route (time attack) under the tunel, 

This can also be seen at the beginning of the race when the camera moves 

Tunel:

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/48363836-e4dc-478e-bf59-f48405f8249b

Race start:

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/2a48dffd-8f77-44c6-a675-568672c8b183

Steps to reproduce:
- choose Time Attack
- select car
- choose Montecarlo course

Core 20240504

**Comment by Kuba-J** [comment]
I think the flickering in Burning Rangers is related to a bug in F1, I didn't want to create a new error report

First mission

https://youtu.be/fbGx7sAyrKA

**Comment by Kuba-J** [comment]
Fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/b26af4d0be14b139ee3d3e9b44ed23040884612f, thanks!

**Comment by real-amano** [comment]
Is Burning Rangers also fixed?

**Comment by Kuba-J** [comment]
Yes
