### ISSUE TITLE
Magic Knight Rayearth (USA) - Stuttering intro

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#204]
Intro start to heavy stutter around 0:20

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/d76aefa1-b47d-47b2-b8d5-50e32b213740

core 20240504

for comparison, real hardware

https://www.youtube.com/watch?v=sa4kn2vluuM

**Comment by Zet-sensei** [comment]
Please retest with core version 2024-06-16.

Seems fine on my systems now after updating.

**Comment by Kuba-J** [comment]
No change for me , tested on dualsdram core

**Comment by real-amano** [comment]
Still a thing (considering the latest sound fixes)?

**Comment by Kuba-J** [comment]
No change

**Comment by Zet-sensei** [comment]
Verified against real hardware, should be closed as resolved.
