### ISSUE TITLE
X-Men vs. Street Fighter (Japan) // Missing flash effect (left side of screen)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#205]
On core 2024-05-16.

When the game is doing some screen flash effects during the attract mode, we can see a small strip of the screen image missing that effect on the left side.

EDIT : Was already present on the previous build too.

**Comment by Kuba-J** [comment]
The issue started with core 20240504

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/4b59d3e595a93e1888e62a8fa1b713f28e828f77
