### ISSUE TITLE
Tempest 2000 (USA) - flashing text when exiting Options menu

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/Saturn_MiSTer#206]
Present in both 20240504 and 20240516.

In the main menu enter the OPTIONS menu and then select EXIT OPTIONS. A dialogue prompt will appear, whether you want to save changes to backup memory or not. The entire text seems to flash rapidly, making it difficult to read. Below are several screenshots of the same screen which is supposed to be static.

![20240516_214322-screen](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/70150033/7edfa36f-e1ae-4e6e-91c8-ee6f627f47fc)
![20240516_214348-screen](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/70150033/2457b65e-eea3-42f2-ab32-5f1d9cebbd52)
![20240516_214349-screen](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/70150033/87c26c46-277a-4f07-9163-2f567116f279)

It should be noted that the same prompt appears when you get a game over and the game attempts to save your high score afterwards. The same bug does not happen in such event.

**Comment by Kuba-J** [comment]
fixed core 20240520 , https://github.com/MiSTer-devel/Saturn_MiSTer/commit/3b5eee9ce5d740d07e126d414b19cf9a84fdc6b5, please retest @Thelypody
