### ISSUE TITLE
Regression graphics glitch MK2

### ISSUE THREAD

**Issue by Fonsie001** [MiSTer-devel/Saturn_MiSTer#207]
Sprites show a glitch and there is a glitch during the ladder of opponents 
Glitch wasn’t there in previous core versions
Tested it on dual ram version 20240516

**Comment by Kuba-J** [comment]
Mortal Kombat II ( USA)

![IMG_20240517_161429299_HDR](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/e0805cf7-7d8f-40db-bdda-a494045df5ba)
![IMG_20240517_161445915_HDR](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/29977f7a-b6cc-4498-a0be-e6b2f834d5d7)
![IMG_20240517_161456885_HDR](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/0396458e-0c09-43e1-894f-7024df66a107)

**Comment by Kuba-J** [comment]
fixed with core 20240520 - https://github.com/MiSTer-devel/Saturn_MiSTer/commit/3b5eee9ce5d740d07e126d414b19cf9a84fdc6b5, please retest

**Comment by real-amano** [comment]
@Fonsie001 and please close the bug if it works for you now
