### ISSUE TITLE
Fighting Vipers // Random Lag Spikes

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#21]
Fighting Vipers (NTSC-J) as of the official October 10th 2023 build is very prone to random lag spikes. It's supposed to run at 60FPS like the other SEGA fighting games, but frequently dips in and out with seemingly no pattern.

**Comment by FGKey2040** [comment]
FWIW this also happens with Fighters Megamix, which uses or builds upon the same engine

**Comment by InfernoHabanero** [comment]
I tested out the new January 13th 2024 unstable build, and it seems like it fixed the random lag spikes. It's a lot more consistent like it should be, so I'm going to close this problem.

**Comment by InfernoHabanero** [comment]
The lag issues are back as of the February 17 2024 build. I'm assuming it's related to the recent coding overhaul that is causing the game to become unstable again.

**Comment by Zet-sensei** [comment]
Build 20240504 seems to work better.

Please retest when possible.

**Comment by FGKey2040** [comment]
Still hitting lag spikes as per update all core

**Comment by Zet-sensei** [comment]
Much better since commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/a4912fec54cc9a202af760653d0a98d88b493dec

Should be fixed, but I leave the final appreciation to the original issue report author.
