### ISSUE TITLE
Doukyuusei - if (Japan) / graphics glitch / Single SDRAM

### ISSUE THREAD

**Issue by saebaryo** [MiSTer-devel/Saturn_MiSTer#211]
- Game : Doukyuusei - if (Japan) 
- Single SDRAM v3.0

- Occurred in the manufacturer's logo after the game starts
- Start with the Start button after the title screen and occur on the next screen

- Saturn_unstable_20240520_129e26
![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/efd96e68-c7e0-4ee0-b0a3-da47a35f7b6f)

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/e28e8496-7ee9-4fe1-8018-a36ae00a41a9)

- Saturn_20240323
![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/dbdb73eb-dcd1-44b4-8091-65a40bf3fd8a)

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/871164f6-411e-4759-a615-32538b3eff98)

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/9186303ca7177e112117b54d56172c7c39b29f01.

**Comment by saebaryo** [comment]
Saturn_unstable_20240616_08a8ef

Thank you. 

Fixed.

![TV CAM 장치_20240616_212625 029](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/8f6fdfa3-57b6-4215-91ae-8153d42159a3)

![TV CAM 장치_20240616_212651 819](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/7116006/2cba35c3-ccac-455a-9176-cdabaa95e6ad)
