### ISSUE TITLE
Mortal Kombat II (USA) - Manufacturer screen - part of an image is shifted   

### ISSUE THREAD

**Issue by bogdysk** [MiSTer-devel/Saturn_MiSTer#212]
Saturn_unstable_20240520_129e26

Game : Mortal Kombat II (USA)

Single SDRAM 

Small part of an image is shifted from right to left:  MIDWAY MANUFACTURING COMPANY and LICENSED BY SEGA ENTERPRISES, LTD

![MK2_Saturn](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/50663999/ef5c8f1a-f556-4d71-b9f0-1ad78f54d0a4)

**Comment by Zet-sensei** [comment]
Should be fixed with core version 2024-06-16.
