### ISSUE TITLE
Daytona USA - No music

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#214]
Daytona USA (original release) doesn't play any redbook audio.  All sound effect are present, but no music.  This is occuring on the 5-20 unstable build.  It's possible I may have a bad bin/cue version of the game, but it works fine with a Fenrir or emulation.

**Comment by Kuba-J** [comment]
Music works fine, single/ dual

**Comment by gleek12** [comment]
I’ll grab a different rom and try it

**Comment by gleek12** [comment]
Ok, tested on a new bin/cue.  Music works fine.  There is no big.  Closing this.
