### ISSUE TITLE
Shining Force III scenario 1 visual glitches during Barrand North Plateau battle

### ISSUE THREAD

**Issue by tnibert** [MiSTer-devel/Saturn_MiSTer#217]
Build observed on: Saturn_unstable_20240520_129e26
Game: Shining Force III scenario 1
Single SDRAM version 2.9

I observed visual glitches in some 3D effects during battle.  The glitches persist through the duration of the battle.  Glitches observed were as follows:
    • When you press B on the world map, a blue circle normally appears and you can navigate like a cursor around the map.  The blue circle did not appear.
    • Waterfalls appear in black.  Screenshot attached.
    • When casting the Blaze L1 spell, a severe visual glitch in the shape of an upside down 4 sided pyramid appeared rather than the usual Blaze animation.  To cast Blaze, use the character Masquerin, move within range of an enemy, then press A, select the spell icon, then select the Blaze icon.  Screenshot attached.

Waterfall:
![IMG20240611213856](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/20619107/b4d963fa-ce2f-4823-a7a2-63f3e043c97b)
Blaze L1:
![IMG20240612211236](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/20619107/95ca4025-e166-4f37-85e6-4c3356ea2bc1)

The specific battle displaying the issue is the Barrand North Plateau battle.  I have attached a save from the beginning of the battle.
[Shining Force III - Scenario 1.sav.zip](https://github.com/user-attachments/files/15803864/Shining.Force.III.-.Scenario.1.sav.zip)

Reproduction steps:
    • Load the attached save
    • Press B, blue circle does not appear
    • Navigate upward on the map to the river, waterfalls appear black
    • Press B to return to the on turn character
    • Move characters toward the Vampire Bat
    • Once Masquerin is in range of the Vampire Bat, press A, select the spell icon on the left, then select the Blaze icon to the top.  Press left on the d pad to reduce the spell power to Blaze L1.  Press A twice to cast the spell on the Vampire Bat.  Pyramid glitch will be observed.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d4f1499435e72245e0f01600ef5f5b5db838c587.

**Comment by tnibert** [comment]
Confirmed fixed on 24.06.20 single sdram manual build from discord.


Just look at that lovely waterfall :)
![IMG20240621213205.jpg](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/20619107/f55889ce-1d69-4f04-91dd-529438dba0ea)
