### ISSUE TITLE
Wipeout XL (Japan) - only digital inputs work.  3d pad setting is non functional

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#218]
The only input setting I can get to work with this game is the “digital” setting.  Setting it to 3d pad results in no controller inputs.

**Comment by gleek12** [comment]
The same issue occurs with MaxTT.  Daytona and Sega Rally both work with the 3d pad, so the issue doesn’t seem universal.

**Comment by srg320** [comment]
@gleek12, SNAC or USB?

**Comment by gleek12** [comment]
USB.

**Comment by gleek12** [comment]
This appears to be fixed in the latest build.  Closing.
