### ISSUE TITLE
[Street Fighter: The Movie] 2D object z order bug

### ISSUE THREAD

**Issue by prlandwehr** [MiSTer-devel/Saturn_MiSTer#219]
Background objects in several stages of Street Fighter: The Movie appear in front of characters rather than behind them. This is most obvious on Ken's stage. Tested on several core builds with screenshot from Saturn_unstable_20240616_08a8ef.

edit: Additional information - toggling VDP2 NBG1 off from the debug options makes the characters legs visible over a black background (removes the ground and shadows as well as the string of lights near the health bars).

![Screenshot 2024-06-17 00-46-50](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/23128459/f48c21c3-099c-425b-88de-fb8ee0cfbe10)

**Comment by Kuba-J** [comment]
From what I remember in this game there is a difference in performance between the single and dualsdram versions of the core. For dualsdram it should work ok.

https://www.youtube.com/live/ua9IFt6rN8Y?si=XiOnex9ai6TmuYUH&t=1560

**Comment by srg320** [comment]
What is the easiest way to reproduce this issue?

**Comment by prlandwehr** [comment]
> What is the easiest way to reproduce this issue?

1. Start Saturn core and load game.
2. Select/Enter Versus Battle mode
3. Select no to prompts
4. Select two characters (p1+p2)
5. Hit R or L for stage selection
6. Select Ken's stage
7. Begin match.

**Comment by prlandwehr** [comment]
> From what I remember in this game there is a difference in performance between the single and dualsdram versions of the core. For dualsdram it should work ok.
> 
> https://www.youtube.com/live/ua9IFt6rN8Y?si=XiOnex9ai6TmuYUH&t=1560

I'm getting the same behavior on Saturn_DualSDRAM_unstable_20240616_08a8ef on my end.
![Screenshot 2024-06-17 02-27-56](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/23128459/e7bc020c-e020-4c79-93ba-1211f7c0a63a)

**Comment by Kuba-J** [comment]
> > From what I remember in this game there is a difference in performance between the single and dualsdram versions of the core. For dualsdram it should work ok.
> > https://www.youtube.com/live/ua9IFt6rN8Y?si=XiOnex9ai6TmuYUH&t=1560
> 
> I'm getting the same behavior on Saturn_DualSDRAM_unstable_20240616_08a8ef on my end. ![Screenshot 2024-06-17 02-27-56](https://private-user-images.githubusercontent.com/23128459/340217035-e7bc020c-e020-4c79-93ba-1211f7c0a63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTc3MjcsIm5iZiI6MTcxODYxNzQyNywicGF0aCI6Ii8yMzEyODQ1OS8zNDAyMTcwMzUtZTdiYzAyMGMtZTAyMC00Yzc5LTkzYmEtMTIxMWY3YzBhNjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5NDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODY2NmY5NjVkYTc2MzUwNWY3OWFmMmM5NzA0OGU1NWEwYzdmODRiMjc1MDlhOGY2NmExZmRmYjg2OWQ5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HV8GVvNCO7Mdt4vrMMmWNQndP5iKICzRSGQNE5Ge94c)

ok then maybe it depends on the stage, thanks for checking !

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d4f1499435e72245e0f01600ef5f5b5db838c587.

**Comment by prlandwehr** [comment]
Seems fixed in Saturn_DualSDRAM_unstable_20240620_174522
