### ISSUE TITLE
Daytona USA: Minor regression on Expert track map graphic during a race.

### ISSUE THREAD

**Issue by METR0lD** [MiSTer-devel/Saturn_MiSTer#222]
There seems to be an extra line of black pixels on the top left of the map graphic on the expert track in Daytona USA. This seems to be a regression, because the issue is not present in the last stable build from March 23rd, 2024. I'm not sure which build it started with, but it is present in the most recent build from June 20th, 2024.

The image on the left shows the issue, and the image on the right is from real hardware. 

<img width="944" alt="image" src="https://github.com/MiSTer-devel/Saturn_MiSTer/assets/147565839/0638fb30-22a3-4aa2-a419-67028e5c651f">

<img width="557" alt="image" src="https://github.com/MiSTer-devel/Saturn_MiSTer/assets/147565839/2ee11a92-b445-4b1a-9c49-ffcca0b01e35">

**Comment by Kuba-J** [comment]
should be fixed with today's core

**Comment by METR0lD** [comment]
Just tested on today's core update, and this is indeed fixed! Great work as always srg320!
