### ISSUE TITLE
Sonic R (No music)

### ISSUE THREAD

**Issue by Macros218** [MiSTer-devel/Saturn_MiSTer#227]
Hey everyone, hope you're doing well, when booting up Sonic R the start menu has a crackling sound and no music plays. I can confirm by going into the settings and doing a sound test that no music plays there either. When entering a race no music plays during the race as well. All sound effects are working however. 

Dual SDRAM or Single? Single 128 MB

Core used: Saturn Release 20240628

Bios used: GameNavi HiSaturn 1.03 BIOS

Steps to replicate:

1. Enter game (should hear crackling in start menu)

EDIT : Issue seems to also be present in Saturn_unstable_20240616_08e8ef. Tried multiple reboots and resets. The game is the North American release.

**Comment by Kuba-J** [comment]
Hi, I checked the bin/cue version with the latest core single and dual. The music works without any problem.

I suggest you obtain the game from another source and try again. 
Also try resetting the settings for core.

**Comment by Macros218** [comment]
Thanks @Kuba-J  a different ROM solved the issue. I do remember that the ROM I had worked with another version of unstable Saturn. The ROM that I got now has all the tracks separated into individual BINS, whereas the one I was using before had it all in one BIN file. Maybe something changed along the way that makes it different for tracks being in one BIN file.
