### ISSUE TITLE
Daytona USA - gui obscured by the car hood

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#228]
When you are in the first person visible hood view, the car hood draws over the top of the map.

**Comment by real-amano** [comment]
Just to make it clear: it is the original run of Daytona USA, not one of the later "Championship" editions?

**Comment by Kuba-J** [comment]
have you compared it with real hardware?

**Comment by srg320** [comment]
On the real console.
![IMG_20240807_104508](https://github.com/user-attachments/assets/493cea94-2eaa-49de-aee1-d0f2c999b5fb)

**Comment by Kuba-J** [comment]
yes, looks same :)

**Comment by gleek12** [comment]
Ok, the screenshot shows this is the same on original hardware.  Thanks for posting that!  Closing this ticket.
