### ISSUE TITLE
Saturn Bomberman: minor glitches

### ISSUE THREAD

**Issue by tjanas** [MiSTer-devel/Saturn_MiSTer#23]
Sound pop during Now Loading screen

Sound pop after “Start!” at the beginning of each stage

After defeating the final boss in a regular single player game, the tile graphics are incorrectly distorted when it zooms out from the exploding space ship.

This was with the 20231010 release build, with a redump bin/cue, using a MiSTerFPGA with dual RAM.

**Comment by tjanas** [comment]
![IMG_8812](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/20304619/3d44263b-bd57-4b2b-aef3-6f3566d992c9)
This is what it looks like after the final boss is defeated when the ship explodes and the camera zooms out.

The following video is what the screen should look like at that point (go to 05:00):
https://youtu.be/qMXkpWoeyYA

**Comment by srg320** [comment]
How to get to the final level/boss?

**Comment by tjanas** [comment]
I just played thru the game from start to finish. I can try again if there is a core build that may resolve the issues.

**Comment by tjanas** [comment]
Try using one of the game cheats to start at level 5: https://gamefaqs.gamespot.com/saturn/198551-saturn-bomberman/cheats

**Comment by tjanas** [comment]
Tested with the latest release (20240323), sound pop is still present after “Start!” at the beginning of each stage. Graphics glitches have been drastically reduced after the final boss, although some still remain in the left and right of the boss ship when it zooms out.

**Comment by Kuba-J** [comment]
Have you tested with unstable mister main?

**Comment by tjanas** [comment]
No, I’ll wait for those changes to get merged into main.

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/4b59d3e595a93e1888e62a8fa1b713f28e828f77 , core 20240520, please retest @tjanas

**Comment by tjanas** [comment]
I'll try doing a replay of this game later this week. Thankfully it's one of the the easiest of Bomberman games.

**Comment by tjanas** [comment]
It seems like the “Sound pop after “Start!” at the beginning of each stage” still remains with this latest unstable core 20240520.

**Comment by srg320** [comment]
> It seems like the “Sound pop after “Start!” at the beginning of each stage” still remains with this latest unstable core 20240520.

What is your build version (menu SYSTEM->ABOUT)?

**Comment by tjanas** [comment]
Nevermind, I was one update behind on MiSTer main. I updated that and now that audio glitch has gone away. :) Now I just need to complete the game.

**Comment by tjanas** [comment]
I was able to do a full playthrough including defeating the final boss, and there were no longer any glitches!
