### ISSUE TITLE
Shinobi X sounds incorrect 

### ISSUE THREAD

**Issue by lucaslbds** [MiSTer-devel/Saturn_MiSTer#232]
In Shinobi's European songs, the flute instrument is wrong and a bit shrill in performance.

**Comment by srg320** [comment]
@lucaslbds, please specify the name of the incorrect sounds (using the Options menu).

**Comment by JaeOfMordor** [comment]
looks like it’s all fixed with today’s update, please retest and confirm

**Comment by lucaslbds** [comment]
Sorry for the delay. Yes, it was fixed in the latest version. And as for the sound you're asking about, srg, in the music for the first stage of the European game, when the Japanese flute starts playing, the sound was shrill. Solved!

**Comment by real-amano** [comment]
@lucaslbds can you close the bug then?

**Comment by lucaslbds** [comment]
Solved
