### ISSUE TITLE
The core is failing some new SCSP tests (Sep-11-2024)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#234]
![20240819_183141-screen](https://github.com/user-attachments/assets/3dc7a76e-af4f-4127-92de-ad7b55664a93)

And the new version of the test, with the source code.

As always, thanks to @celeriyacon for all the hard work and sharing the new test with us.

EDIT : Thanks to Wark91 on Discord, I've uploaded the wrong snapshot as the last test wasn't ready on that one.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/569bb91531861f5918126b8ef78fb9b67536d681
![20240824_140800-screen](https://github.com/user-attachments/assets/1f38edc7-f634-441b-b485-9bdd606787d4)

**Comment by Zet-sensei** [comment]
I'm reopening the issue as @cleriyacon have shared a new version of the test.
And the core fails on two of them now.

[scsptest-aug27-2024.zip](https://github.com/user-attachments/files/16762763/scsptest-aug27-2024.zip)

![20240827-screen](https://github.com/user-attachments/assets/c6b1deb9-0d5e-42cd-ab84-7bb2b54c8ba3)

**Comment by srg320** [comment]
I was waiting for the EG tests.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/51557a7d389aec34d9f68326a70e29a9c5c5b4e6.

**Comment by Zet-sensei** [comment]
![20240911_193006-screen](https://github.com/user-attachments/assets/1b89f4b5-686d-4461-9a91-c44ab17d60c3)
![20240911_193029-screen](https://github.com/user-attachments/assets/617305be-1df3-4b00-a33b-d27fbb8f3a89)
![20240911_193037-screen](https://github.com/user-attachments/assets/8fa1292e-15ff-46bc-a90e-e874e6a0527d)
![20240911_193048-screen](https://github.com/user-attachments/assets/8e215499-6285-45d0-bf4a-e75d0f25f9f9)
![20240911_193102-screen](https://github.com/user-attachments/assets/af036772-9654-472a-8e01-1f8a689345a9)
![20240911_193113-screen](https://github.com/user-attachments/assets/9111720b-2261-4cb7-bc1c-7ceede1a2c81)
![20240911_193135-screen](https://github.com/user-attachments/assets/ea210f96-382d-4bc9-90ca-736b0616ab18)

**Comment by Zet-sensei** [comment]
Thanks to @kuba-J for the screenshot.

![20240918_205923](https://github.com/user-attachments/assets/b411c356-0f10-4a91-956a-c8b53fa10cec)

**Comment by Zet-sensei** [comment]
All tests passed with 2024-10-08 core version.
@celeriyacon was informed a little bit before.

![20241008_113953-screen](https://github.com/user-attachments/assets/36545f91-8bb6-434a-8be1-eb0afcbb55ab)
