### ISSUE TITLE
Digital Monster Ver. S not loading. 

### ISSUE THREAD

**Issue by Waifu4Life** [MiSTer-devel/Saturn_MiSTer#236]
Version (or build number)
20240817

Single or Dual SDRAM?
Single (128MB)

Steps to reproduce
1- Load the game
2- Black screen

Expected Behavior
The game to load

Actual Behavior
Black screen

Additional Context
I dump this game myself and it runs on the mednafen emulator.

**Comment by Zet-sensei** [comment]
Can confirm (and Kuba-J too).

**Comment by real-amano** [comment]
@Waifu4Life new fixes are pushed to git. Can you re-test and close the issue if it works for you now?

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1419ef98199c327394df1487179af048f8b036bf

**Comment by real-amano** [comment]
@Waifu4Life Can you confirm and close the issue if it works for you now?

**Comment by Kuba-J** [comment]
> @Waifu4Life Can you confirm and close the issue if it works for you now?

@real-amano I think the waifu already knows he has to check it, you don't have to rush people like that, it's a bit annoying.

**Comment by Waifu4Life** [comment]
Hello, just tried it with the latest unstable, working fine now. All 112 Saturn games that I have on my MiSTer are now playable. Thank you. Now the only thing left is to wait for Saturn Light Gun support 😋
