### ISSUE TITLE
Idol Janshi Suchie Pai II // Inverted render mask (introduction)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#237]
At around second 40 on the introduction of the game, the portaits are drawn around kana instead of inside of them.
Most probably a masking effect with the VDP is incorrect here.

Tested on core version 2024-08-17.

![idoljanshi2-saturn-20240817](https://github.com/user-attachments/assets/16205609-6a7e-43cd-b54c-7dad7db0ddf5)

Expected behaviour 
![idoljanshi2-yt](https://github.com/user-attachments/assets/02b1b34e-8999-4319-aba9-e0a6d329b766)

Thanks to KennyL for finding that issue on Discord.

**Comment by real-amano** [comment]
And probably fixed already ;)

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/ad253fa212ac6258c5c7e61cf05dd36a2ee2a5cb
