### ISSUE TITLE
Grandia (JP): Movement desync between floor and foreground objects

### ISSUE THREAD

**Issue by unlimitedcodeworks** [MiSTer-devel/Saturn_MiSTer#238]
Lower left is captured using Saturn_unstable_20240824_111077, others are captured from real hardware:

https://github.com/user-attachments/assets/5dcb2bcb-d874-4ff6-8cd6-9fc4f1d9a2d3

It looks like there might be a synchronization issue between the VDPs and they get updated/drawn independent from each other on MiSTer, while they update together on real hardware.

**Comment by unlimitedcodeworks** [comment]
After closer inspection this just seems to be a duplicate of https://github.com/MiSTer-devel/Saturn_MiSTer/issues/210, just a bit more pronounced due to slowing down the video.

**Comment by Kuba-J** [comment]
I took the liberty of using the videos from the topic on flicker

videos has been slowed down 

video with flickering - desynchronization 

https://github.com/user-attachments/assets/fd8269da-ca99-40d0-a339-9522b9cdec48

video without flickering - synchronization is ok

https://github.com/user-attachments/assets/dda9b355-d571-4726-a1f6-63e3aabb93e7

**Comment by Kuba-J** [comment]
I took the liberty of using the videos from the topic on flicker

videos has been slowed down 

video with flickering - desynchronization 


https://github.com/user-attachments/assets/eb5ae374-db68-4c1d-b562-cc862ba89fc5



video without flickering - synchronization is ok



https://github.com/user-attachments/assets/28a71fdd-d0f5-4f3c-96f5-a251826a447e

**Comment by Kuba-J** [comment]
Sorry, I put the post again , because I plugged in the wrong video before and had trouble editing.
