### ISSUE TITLE
No battle effects or voice lines in virtua fighter 2

### ISSUE THREAD

**Issue by FGKey2040** [MiSTer-devel/Saturn_MiSTer#24]
Announcer still works

**Comment by Kuba-J** [comment]
fixed core 20240307 https://github.com/MiSTer-devel/Saturn_MiSTer/commit/577c12f1f3c379f9cae8e4fdf6f69c8174d887c5

**Comment by JaeOfMordor** [comment]
> Announcer still works

close this issue please

**Comment by FGKey2040** [comment]
There are voice lines and battle effect noises that don’t play properly in the build for me still. The announcer is not the reported issue

> > Announcer still works
> 
> close this issue please
