### ISSUE TITLE
X-Men vs. Street Fighter (Japan) // REGRESSION - Infinite loop on the intro

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#244]
On core 2024-09-02, the introduction of the game can't be played correctly anymore (infinite loop of the first seconds) and the game can't be played either.

**Comment by Zet-sensei** [comment]
The game regressed between 2024-08-17 & 2024-08-24 after some tests.
Maybe SCU related.

**Comment by Zet-sensei** [comment]
@kuba-J tried to revert the SCSP to 20240817 state on core version 20240902.

The game works once again.

**Comment by Zet-sensei** [comment]
After some days of tests (and many internal builds) by reverting the 2024-09-02 SCSP code to the 2024-08-17 state & adding once more each functionality one by one + cheking each time if it could break some games.

I've probably seen something breaking X-Men vs. SF around here (line 448 to 475).

![Loop](https://github.com/user-attachments/assets/9101d152-8746-44f6-8089-1c801a7b1c1f)

That part of the code seems to break X-Men vs. SF during the introduction like explained earlier on the issue tracker.
If I inject the 2024-08-17 version of that part of the code, the game introduction could be seen completely (without sound).

Maybe the issue with SEGA Rally could be related too, as the whole 2024-08-17 SCSP code works fine for that game, but not the 2024-08-24 and so on.

**Comment by Kaligulin** [comment]
Hi, my audio continues to do strange things, even with the latest update, the audio keeps skipping in the intro and cutting out, the last functional core with this game was on 8/17/2024. In the fights within the game, the audio also skips seconds.
Regards.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/8e72ae7cc15aa4818ea4c43ec989e3ad4fe9d3c7

@Kaligulin please update to the new version as of 2024-09-18 (2nd compilation).
