### ISSUE TITLE
Battle Garegga Medal Sprite Regression

### ISSUE THREAD

**Issue by EzDzzIt** [MiSTer-devel/Saturn_MiSTer#248]
In-game in BG, after selecting the 'screenmode' option setting seen in the attached image, certain sprites don't get drawn correctly during gameplay (for example, medals and bullets- example of a medal sprite in this mode attached).

All other screenmode options seem to be working fine, only this "zoomed-out" screenmode breaks sprites as far as I can tell. A couple users confirmed similar behavior after selecting this screenmode.

![IMG_2526](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/143894375/73ba27db-0085-4a6a-860f-2f85f1b33a18)
![IMG_2527](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/143894375/21d8d9d5-0fa5-4a2e-be8f-4e941927f1aa)

_Originally posted by @EzDzzIt in https://github.com/MiSTer-devel/Saturn_MiSTer/issues/184_

Looks like this issue might be back for current core iterations; only for certain gold circular medal sprites at this point. Tested on the 6/28 and 9/2 builds. ![image](https://github.com/user-attachments/assets/ad103dfb-402d-44d5-96d0-3fcfe302fd90)

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/2a527bc15e93b9ec0b68d83c98279e711d552778

Please restest with the last unstable version.

**Comment by EzDzzIt** [comment]
Hey @Zet-sensei i tested and the medals do look better. I noticed that the missile shots do appear more broken up however (these are the gray shots you may see in the stage one boss) ![image](https://github.com/user-attachments/assets/6f4c5df3-db83-4de1-a6ac-d2385a7dbc5f)

**Comment by Kuba-J** [comment]
should be fixed now, commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d6c450e24814ddb83d90ab29bae55eed92799569

**Comment by EzDzzIt** [comment]
Will test today!

**Comment by EzDzzIt** [comment]
Looks great.
