### ISSUE TITLE
Manx TT SuperBike (USA/JP) - problem with starting the game

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#250]
Manx TT does not work if it is run as the first game on the core = black screen after SEGA logo. Works after a resets or when run after another game.

**Comment by Kuba-J** [comment]
House of the Dead is a second game with the same problem

**Comment by rickshanahan** [comment]
I'm having this problem with house of the dead, but it doesn't matter if I run something else first or restart, I always get a black screen after the sega logo.
