### ISSUE TITLE
Rayman (USA) // Crashes after defeating the final boss

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#253]
A user on Discord (Rei) reported a crash after defeating the final boss of the game.

![20241002_085240](https://github.com/user-attachments/assets/d41b3b3c-47ac-404d-9689-723248b0225d)

Some more info from my part that could help at some point.

I remember reading the same issue on some other software emulators some years ago, like Mednafen.
Seems to be related to a VDP1 coordinate precision bug.

The solution was to implement an accurate reproduction of VDP1 drawing of excessively-large primitives.

EDIT ; Multiple previous versions of the core tested too, seems consistent and not a regression.

**Comment by Zet-sensei** [comment]
Save file for getting into the last level.

[Rayman (USA) (R2).zip](https://github.com/user-attachments/files/17224077/Rayman.USA.R2.zip)

**Comment by srg320** [comment]
> Save file for getting into the last level.

Thanks.

**Comment by Zet-sensei** [comment]
Doing the last level & getting into the final boss remain difficult.

I don't have any other option with the core for helping much further (no save state) + letting you see directly the issue.

**Comment by Zet-sensei** [comment]
[Rayman (USA) (R2).zip](https://github.com/user-attachments/files/17269406/Rayman.USA.R2.zip)

Supersedes the previous save, as I've added 99 lives and should be 'easier' to go to the and of the game.

**Comment by srg320** [comment]
> Supersedes the previous save, as I've added 99 lives and should be 'easier' to go to the end of the game.

Thanks, but I already passed the final boss and fixed the issue.)

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d6c450e24814ddb83d90ab29bae55eed92799569
