### ISSUE TITLE
Alien Trilogy (USA) - Green filter is shifted on the screen - level 11

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#254]
Core 

![20241009_223607](https://github.com/user-attachments/assets/08887d0b-2e3a-4427-ba26-b04f06dc7a89)

Real hardware 

![Screenshot_20241009_225903_Discord](https://github.com/user-attachments/assets/450870f8-0325-40ec-ba29-3aec0120de80)

Code to level 11 - Enter password  FLYT011 in the options and start the game

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/551e8e04a3a724dd849bf98f91c1fe0b35fac943

**Comment by Kuba-J** [comment]
Fixed
