### ISSUE TITLE
Virtual Hydlide (USA) - bug with white lines

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#255]
As you explore the area, you will occasionally see white lines. 

Probably the easiest way to reproduce this is by turning the character to the right and left , trying in several places

I have not observed this error in any other game. 

![Zdjęcie WhatsApp 2024-10-11 o 07 56 40_e337444d](https://github.com/user-attachments/assets/0c9d186f-0ecf-4e5f-b021-dc829bec3733)
![Zdjęcie WhatsApp 2024-10-11 o 07 56 40_f1d8c19e](https://github.com/user-attachments/assets/054d1355-98be-4d45-ad6d-7b2274c5d80f)

https://github.com/user-attachments/assets/7357c2c4-4bb5-41e8-bbb3-5c86bb41e242

**Comment by Kuba-J** [comment]
There is a similar effect in the game Willy Wombat (J) when you stand against a wall and rotate the camera. I don't know if this also occurs on the real hw.


https://github.com/user-attachments/assets/dbf15339-b5d0-456e-b6ff-dbccd9bc3d87

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/115fec3286b754aab41a582a00171b46b582590a

**Comment by Kuba-J** [comment]
Fixed
