### ISSUE TITLE
Dualsdram core version issues

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#259]
Hi, I checked the dualsdram core version, in the sdram version comparison: 

128mb v2.9 + 32mb v2.2 - core does not work 

128mb v2.9 + 128 v2.4 - I have errors e.g. in Dead or Alive intro.

![20241030_163203](https://github.com/user-attachments/assets/3d384a83-7cd7-444a-b2c6-56e111111c35)

128mb v2.9 + 128mb v2.9 - core works fine

**Comment by srg320** [comment]
What is the first (main) module and what is the second module?

**Comment by srg320** [comment]
Try this build 
[Saturn_DS.zip](https://github.com/user-attachments/files/17576963/Saturn_DS.zip)

**Comment by Kuba-J** [comment]
> Try this build [Saturn_DS.zip](https://github.com/user-attachments/files/17576963/Saturn_DS.zip)

Thanks ! This core fix the problem
