### ISSUE TITLE
Grandia (JP) - broken sound in fmv intro

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#260]
Towards the end of the fmv intro in Grandia, the sound is broken, a loud cracklings sound is heard

**Comment by Zet-sensei** [comment]
I can't seem reproduce that issue on my v2.9 Dual RAM system and that core version.
https://github.com/MiSTer-devel/Saturn_MiSTer/issues/259#issuecomment-2447931077

**Comment by Kuba-J** [comment]
I only tested the Japanese version. To be more precise, it is about the intro after selecting a new game.

**Comment by Zet-sensei** [comment]
I can hear the problem too on my system, only the JP version seems to be affected.

**Comment by Kuba-J** [comment]
Thank you for checking !

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/aa0b37dc9e7d089aa932e1f8620fc660ef451896
