### ISSUE TITLE
Sonic Jam - green screen browsing  manuals

### ISSUE THREAD

**Issue by FGKey2040** [MiSTer-devel/Saturn_MiSTer#263]
After viewing a page in the digital manuals (options after game select), accessing a page to read with A or C then hitting B to go back presents a green screen which can only be removed by pressing left or right to flick pages (single RAM)

**Comment by Zet-sensei** [comment]
Should be fixed with commt https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1cf9e1a313521d466d1f76419cfc9998bb7ef10a

**Comment by FGKey2040** [comment]
It is!
