### ISSUE TITLE
NBA Jam Extreme (USA) // [NOT A BUG, IT'A FEATURE] Incorrect render of the 3D basket ball in-game

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#267]
There is a problem with the render of the 3D ball duing the gameplay.

The ball is rendered as a triangle with a rose tinted color.

**Comment by Kuba-J** [comment]
Nice find!

**Comment by srg320** [comment]
> Sorry for the time taken on that "feature" of the game.

But found a issue with resetting the date)
