### ISSUE TITLE
Virtual On (US) freezes during replay

### ISSUE THREAD

**Issue by carnage-asada** [MiSTer-devel/Saturn_MiSTer#270]
It might be the CHD, but I tested Virtual On (US) using the most recent unstable build (20241030). The game freezes during replays. Tested both the single and dual RAM cores. Appears to work fine using the previous unstable build (20241008).

**Comment by Zet-sensei** [comment]
I can fix the issue by reverting the YGR019 to the 10-08-2024 version and recompiling the core with it.

So, maybe something to check there.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1caa59276a4112da74aec18749291ea628d4a488

**Comment by Zet-sensei** [comment]
Confirmed as fixed by multiple testers since then, waiting for closing the ticket from the original author.

**Comment by carnage-asada** [comment]
Confirmed working with the newest core. Closing ticket. Thank you!
