### ISSUE TITLE
Linkle Liver Story graphic artifacts

### ISSUE THREAD

**Issue by T0DS** [MiSTer-devel/Saturn_MiSTer#28]
Artifact appearing across the screen right after leaving the starting cave.
![20231015_103233-boot](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/d2394aac-3937-47e3-81c9-1a20931d057a)
Shadows under trees as well as some trees sprites flickering or disappearing, usually when they are near the edge of the screen.
![20231015_104944-boot](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/04d61fa3-03d9-4487-89fa-e3413454e480)
![20231015_104951-boot](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/57697cba-bddf-4b3c-873e-8668793166d9)
![20231015_105027-boot](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/148105ea-10d0-492c-b086-e9e04138bb42)
![20231015_105044-boot](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/8f14d78b-2d38-4c3d-8c68-1c6f7100e75e)

**Comment by Zet-sensei** [comment]
A fix for the game was pushed today.
Commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/4fd8b49d5f18443cf47b7d17a90c382ace57d610

Could you please recheck the game on your side and update the issue ?
Thanks.

**Comment by T0DS** [comment]
All the issues above have been fixed, thanks!

I have found however another issue, which happens both in the old build of the core as well as the new one. When entering the starting cave for a second time, there are pillars of light shining from the ceiling into the ground. Standing on them causes the floor to be partially visible trough the character sprite.
Here is a screenshot showing this:

![20240110_222319-screen](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/271b8c26-eae0-44f4-94e3-5a4685ff91df)

Here is a screenshot of the game running in mednafen, without the transparency bug:

![Linkle Liver Story (Japan)  T-En by Aishsha v1 0 -240110-224238](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/38330443/ea753cc3-bbcf-4983-a420-1b0710f774c3)

**Comment by srg320** [comment]
Leave this one.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/e26aca3b0eb535acb1773deaf6245d67a9fa4f4f

Please retest and update the issue.

**Comment by T0DS** [comment]
Confirmed issue fixed, that was fast, thanks a lot!
