### ISSUE TITLE
Panzer Dragoon (NTSC-U) // Flickering Text In Intro

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#280]
https://streamable.com/6062n1

Tested using the 11-06-2024 dual RAM build using two 128MB 2.9 RAM modules.

**Comment by Zet-sensei** [comment]
Confirmed as fixed by multiple testers on core version 2024-11-16.

Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/77737b3549e2d40959f149d2328fc4cbf7628ce6
