### ISSUE TITLE
Digital Dance Mix Vol. 1 - Namie Amuro (Japan) // Some slowdowns on Single RAM build, even with FAST timings option (2024-11-16)

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#281]
The characters don't move at all, but Namie's mouth still animates after selecting START on the DIGITAL DANCE part.
.

**Comment by Zet-sensei** [comment]
From a user on Discord.

*I've figured it out. It's the backgrounds that are causing the issue. Namie dances just fine with the plain white background, but any of the other stage options (in either Digital Dance or Sing It mode) will cause Namie (and background dancers depending on stage) to remain stuck in her starting pose, and for the music to keep looping the first few seconds or so.*

**Comment by srg320** [comment]
Оn original hardware:

https://github.com/user-attachments/assets/32dedee4-1f31-45e9-bdd5-8d9b04188b9a

**Comment by Zet-sensei** [comment]
Yes, the character is moving using the blank/white background, even on MiSTer.

All other selectable backgrounds are getting the character stucks on the animation on the DIGITAL DANCE mode.

**Comment by srg320** [comment]
This game is very dependent on the accuracy of the timings. In dual sdram build the game should work as intended. In single sdram build the game only works if you select the menu Hardware->Timing to Fast. Please check.

**Comment by Zet-sensei** [comment]
indigo (the original issue finder) have seen that too with the current core, when testing with the 2024-11-16 Single RAM build.

Thanks for the confirmation.

**Comment by Zet-sensei** [comment]
With the option "Hardware->Timing - Fast", it works with some quick slowdows compared to the original hardware & the Dual RAM build.

At least the Dual RAM build is working as intended.

**Comment by srg320** [comment]
> With the option "Hardware->Timing - Fast", it works with some quick slowdows compared to the original hardware & the Dual RAM build.

Well, I can't do any better for a single sdram build.

**Comment by Zet-sensei** [comment]
That tech demo/game is interesting for heavy-testing the core and the implementation of most of the VDP functions/timings.

So I'm closing the issue ticket after your last comment.

Thanks for all you've have done so far, once again.
