### ISSUE TITLE
Sonic Wings Special [original game bug] - bug when cycling through screen modes

### ISSUE THREAD

**Issue by real-amano** [MiSTer-devel/Saturn_MiSTer#293]
Turns out that those are issues of the original game on real hardware

--------------------------
Original report:
QmTech Mister, 128mb, single RAM builds. Tested on HDMI Out.

There are different screen modes in the options menu of the game: Normal - Arcade - Interlaced

The Arcade mode is for rotating the TV manually but is not viable ATM because my screen can just be tilted clockwise and Arcade mode needs anti-clockwise tilting. This is tracked in bug #148.

But when testing this Arcade mode to know whether this game can be used with my monitor, I noticed two possible (other) bugs when cycling through these options:
1) when cycling too fast the game becomes unresponsive and goes into a short buggy loop (but finally manages to restore itself to a stable state again). I guess it didn't love to be switched to Interlaced and back to non-interlaced too fast.

2) the screen size available on the monitor shrinks considerably when being switched to Interlaced. I don't own the original game and thus cannot verify on real hardware. But I guess, Interlaced mode should show a higher resolution at the same visible size.

**Comment by srg320** [comment]
On original hardware:

https://github.com/user-attachments/assets/4054c56b-2e3f-42ee-b4a1-17b831c557f0





> 1. when cycling too fast the game becomes unresponsive and goes into a short buggy loop (but finally manages to restore itself to a stable state again). I guess it didn't love to be switched to Interlaced and back to non-interlaced too fast.

When I hold the right/left button, the same thing happens on the Mister as on the video from the original (second half).

**Comment by real-amano** [comment]
Wow. Thus an original game bug, perfectly emulated ;)

But the other issue is the small screen size in-game when choosing the Interlaced mode. That seems very non-intended but might be an original game issue as well.

**Comment by real-amano** [comment]
Closed as invalid (original game bug)
