### ISSUE TITLE
Nights into Dreams... Boss battle 2 graphical issues

### ISSUE THREAD

**Issue by carnage-asada** [MiSTer-devel/Saturn_MiSTer#296]
Ran into an issue during the Boss Battle 2 with Puffy (after playing Splash Garden). Whenever I fly close to the ceiling or floor, the screen only renders the background, floor and ceiling. This only happens running the Dual RAM build (2024-12-01). Single RAM appears to work fine. Tested both US and Japan versions of Nights and got the same issue.
![Boss Battle 2 example 1](https://github.com/user-attachments/assets/b31523d5-fe67-4d16-8cc5-7f80abad2790)
![Boss Battle 2 example 2](https://github.com/user-attachments/assets/6b383acc-511e-4cdd-bc2b-680f9befb11d)
![Boss Battle 2 example 3](https://github.com/user-attachments/assets/190c008b-183c-4575-bedb-23712fa204a5)

**Comment by Zet-sensei** [comment]
It will be better to add a save for getting faster to that point inside the game.
Thanks.

**Comment by srg320** [comment]
For someone who has never played this game, explain how to complete a level. I randomly fly around the level for about 20 minutes and eventually died.

**Comment by carnage-asada** [comment]
The quickest way to complete a level is to collect 20 blue chips, They're these blue orbs that are scattered throughout the levels:
![PXL_20241204_172413884](https://github.com/user-attachments/assets/54282d1b-4319-4ea7-91dd-546594ffb519)

Once you have 20 blue chips, you can deposit them into these capsules by flying into them. The capsules act as a bank, you don't necessarily need to collect 20 chips at once. You can come back and drop off more chips until you reach 20:
![PXL_20241204_172734846](https://github.com/user-attachments/assets/d577c06e-89fb-472f-abf7-fa9d414d7a7b)

Once the capsule has 20 chips, it will destory itself and give you a multicolored orb:
![PXL_20241204_175710222](https://github.com/user-attachments/assets/6206b089-e1e3-4d3c-a7e0-2acd4ad6b8b0)

You can fly back to the shrine to complete the round. Do this 4 times to complete the level and go into the boss battle
![PXL_20241204_172605131](https://github.com/user-attachments/assets/63a64742-c3fc-4c08-b2f7-2582642d8b24)

If that it wasn't clear (sorry), this is how the game explains it.
![Screenshot 2024-12-04 100209](https://github.com/user-attachments/assets/47e8fcfc-7374-448c-a116-e12e2907cb16)

**Comment by srg320** [comment]
Thank you for the detailed instructions.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/d4f88fde3bf0a52a710c28d38627ea0875932988

Please retest and report back.

**Comment by carnage-asada** [comment]
Boss battle appears correctly on DualRAM 20241208. Thank you! Closing ticket
