### ISSUE TITLE
Shin Shinobi Den (Japan) freezing before title screen

### ISSUE THREAD

**Issue by allen77710** [MiSTer-devel/Saturn_MiSTer#30]
Shin Shinobi Den (Japan)
After the opening animation is played, the title screen freezes and the game cannot be entered.
Shin Shinobiden freezes after pressing start during intro

Expected Behavior
The game should not freeze after intro

Current Behavior
Shin Shinobiden freezes after pressing start during intro

Steps to Reproduce
Launch Shin Shinobiden
Press start during intro

Context (Environment)
Single SDRAM
Latest official build of the core

**Comment by Toryalai1** [comment]
This is not a core bug. Go to OSD menu and set player 2 to none. Shin Shinobiden has a bug where if second controller is connected, it will crash. You can close this ticket

**Comment by allen77710** [comment]
Thank you, that's indeed the case,I will close this ticket

**Comment by allen77710** [comment]
Thank you, that's indeed the case,I will close this ticket



                       
原始邮件
                       
                     

发件人："Toya"< ***@***.*** &gt;;

发件时间：2023/10/19 14:08

收件人："MiSTer-devel/Saturn_MiSTer"< ***@***.*** &gt;;

抄送人："allen77710"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [MiSTer-devel/Saturn_MiSTer] Shin Shinobi Den (Japan) freezingbefore title screen (Issue #30)




 
This is not a core bug. Go to OSD menu and set player 2 to none. Shin Shinobiden has a bug where if second controller is connected, it will crash. You can close this ticket
