### ISSUE TITLE
(regression) Panzer Dragoon sprite flicker as boss appears.

### ISSUE THREAD

**Issue by JaeOfMordor** [MiSTer-devel/Saturn_MiSTer#300]
Saturn DualSDRAM 20241202

at the end of stages 1, 2, 3 & 4 everything on screen that is not a background layer flickers as the boss fight loads in.

stage 1 it lasts a fraction of a second, but stage 2 is much more noticeable, same with the rest of the levels.

hope this information is of use to you.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/10f1994d3740f9bbf282583c00f2caee3ffba528

Will need a restest and a feedback.
Thanks.
