### ISSUE TITLE
Last Bronx slowdown

### ISSUE THREAD

**Issue by gleek12** [MiSTer-devel/Saturn_MiSTer#302]
Playing Last Bronx exhibits severe slowdown.

This was tested using the Dec 2nd single SDRAM build.  Interlacing was set to Bob.

**Comment by srg320** [comment]
Same as #107, #21 and #281.
This games have a similar engine for calculating and drawing player polygons. This engine depends on the accuracy of the work RAM. It is not possible to provide the necessary RAM timings in a single sdram build.

**Comment by real-amano** [comment]
That should be one of the games that needs a dual RAM setup. But I will potentially profit from the FAST timing setting in current nightly builds. Did you try that?

**Comment by gleek12** [comment]
The fast settings appears to have a very positive effect!  Almost no detectable slowdown in the brief testing I did.
