### ISSUE TITLE
Slam 'n Jam '96 Featuring Magic & Kareem (Japan) // Horizontal lines appearing when zooming/dezoomig the playfield

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#304]
On core 2024-12-08, when I checked more carefully an Exhibition match for some minutes.

I can see some horizontal lines en the whole screen (1 pixel large) that could appear when zooming/dezooming during the game play.

**Comment by srg320** [comment]
Can you show a screenshot?

**Comment by Zet-sensei** [comment]
I've found the problem.
It was on my side.

kuba left a test build the other day with a partial revert for VF2 and Tomb Raider with the same build date too on Discord.
And I used that build by error (chose to fast the core on the main MiSTer menu) instead of yours.

The game is working fine after a correct retest.

Issue classified as invalid.
