### ISSUE TITLE
Dezaemon 2 (User Game Loading)

### ISSUE THREAD

**Issue by DrAvedi** [MiSTer-devel/Saturn_MiSTer#306]
There's a wealth of user generated content for Deza 2 and I'm eager to get it running on MiSTer, but I'm unsure if it's possible to load user games from the Saturn's internal storage by placing the user-game saves in the Saturn save folder. Using cartridge saves is a method used by many on real hardware, but afaik that isn't a feature included in this core yet.

this is a somewhat niche request, so I understand if it isn't gonna happen

nonetheless, I wanted to ask in case it's already possible/not-too-crazy to implement going forward

**Comment by srg320** [comment]
Need a detailed description of the actions and files to test.

**Comment by DrAvedi** [comment]
Your latest nightly has made playing the user games possible via the backup cart

I can document the steps needed to get them running if you like. It's a bit involved, since there isn't a way to swap backup "cartridges" within a game as it is implemented rn. I needed to make a new instance of the Deza 2 rom for each desired .sav, which then allowed me to generate multiple .sav files each containing user games for the Deza 2 engine.

Thanks for your work!

I'll close this issue now
