### ISSUE TITLE
Sega Rally Championship (USA) - Sound Issues

### ISSUE THREAD

**Issue by ransom1122** [MiSTer-devel/Saturn_MiSTer#33]
There seems some kind of common issue with this game using single v2.5 128mb... Some users say sound works with this ram other users say it doesn't.

Basically the sound cuts out after seconds and there's no music..

My ram is v2.5 128mb 140mhz

I'm hoping you can get to the bottom of this plaguing issue with the great classic Saturn game.

**Comment by bootsector** [comment]
Same here. v2.5 128mb 140MHz from reputable/recommended US seller. CDDA seems to get lost at some point during game play. I could also see the same issue with Street Fighter Zero 3.

**Comment by venalaine** [comment]
I have tested SRC with two Mister setups (both have same kind of RAM, same bios and same game files). One plays music and other does not.

**Comment by Jlmbles** [comment]
No issue on 128mb V3.0

**Comment by Zet-sensei** [comment]
Please retest with a recent core revision (20241013) and update the issue.

Some users are reporting that problematic games with cutting music on v2.4/v2.5 are fixed or far better now, after a DDRAM controller rework commit.

**Comment by jsmolina** [comment]
> Please retest with a recent core revision (20241013) and update the issue.
> 
> Some users are reporting that problematic games with cutting music on v2.4/v2.5 are fixed or far better now, after a DDRAM controller rework commit.
> 
> EDIT : At least 3 users on Discord said the game is working now with music on their MiSTer systems (all with v2.5 Single RAM).

I do have 2.5 128 Mb and even installed a Dual SDRAM 32 Mb, but still Sega Rally randomly looses music and engine sound in latest unstable version.

**Comment by sroccaserra** [comment]
Thank you, I tested again, v2.5 128Mb, with 20241013.

For me, in Sega Rally, any sound (music, effects, voices) starts and after 0.5 second it cuts. So the game is mostly silent with sometimes an effect that starts and is cut almost immediately. Both JP version with JP bios 1.01, and US version with US bios.

Other games I tested sound good though (Batsugun, Daytona - low sound but works), but I can't remember exactly if they had sound problems with my setup and the previous core. It's so nice to be able to play Batsugun on a CRT again after all those years by the way ❤️

**Comment by jsmolina** [comment]
See here a demonstration
It will mostly keep the audio until the end of the video
https://www.youtube.com/watch?v=iOhaZvrUq5M

**Comment by ransom1122** [comment]
Still no fix for this game. Music doesn't work and sound still cuts out on all saturn cores normal and latest beta v 24.02.17..

Easily go into ylthe games options and sound and test bgm l, it fails miserably..

The one game I've always wanted to play on mister and it's never worked...

Is there still hope for a fix? 
![20240219_113957](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/28079950/1da65c3d-c5a2-4307-b342-87cdaca61ba8)

**Comment by srg320** [comment]
Try this build.
[Saturn.zip](https://github.com/user-attachments/files/15787273/Saturn.zip)

**Comment by Kuba-J** [comment]
More people on discord are reporting that this core works properly now with their sdram 2.5 or MMS

**Comment by real-amano** [comment]
@ransom1122 , can you test with the special Saturn build and close the bug if it is fixed for you?

**Comment by AktaneDev** [comment]
> Try this build. [Saturn.zip](https://github.com/user-attachments/files/15787273/Saturn.zip)

Works awesome for me! Several games that didn't work months ago on my 3.0 ram mister now work great with what seems to be near perfect sound such as Cotton 2, Sega Rally, Soukyugurentai, and Layer Section 2.

**Comment by real-amano** [comment]
@ransom1122 , can you test again and close the bug if it is fixed for you?

**Comment by ransom1122** [comment]
> @ransom1122 , can you test again and close the bug if it is fixed for you?

Issue now Fixed.... with core Saturn_20240620.rbf
