### ISSUE TITLE
Alone in the dark 2 - speed issues

### ISSUE THREAD

**Issue by TheGrimaceMWM** [MiSTer-devel/Saturn_MiSTer#35]
Games speed runs incredibly fast during some scenes. Very hard to start game because it flys through static texts screens but pounding start and the a button can get you past it, but the game us unplayably fast after this. 

Intro also speeds through all text/credit screens and some animations are too quick.

**Comment by Kuba-J** [comment]
should be fixed with today test core 20240406 https://github.com/MiSTer-devel/Saturn_MiSTer/commit/61c8a8577b07d2557b1b83d374f6edf735f213e6, please retest

**Comment by TheGrimaceMWM** [comment]
Looks good to me!
