### ISSUE TITLE
Super Puzzle Fighter II Turbo - music disappears

### ISSUE THREAD

**Issue by venalaine** [MiSTer-devel/Saturn_MiSTer#37]
USA version. Music plays when the game starts but disappears soon. Otherwise the game works just fine. 

Tested with v2.5 128MB ram (stable at 140 MHz). 

Still works fine on some setups with same kind of RAM. So, same kind of issue as https://github.com/MiSTer-devel/Saturn_MiSTer/issues/33

**Comment by Zet-sensei** [comment]
Could you restest the game with the recent 20240113 core version ?
As we could hear some better performance on music with other testers on SEGA Rally too.

**Comment by srg320** [comment]
@venalaine, try this build.
[Saturn.zip](https://github.com/user-attachments/files/15787260/Saturn.zip)

**Comment by real-amano** [comment]
@venalaine , no dice?

**Comment by real-amano** [comment]
@venalaine , no dice? Did you try? The recent build might have nailed the Saturn audio.

I guess srg might remove the readme line that many games have incorrect sound.

Please close the bug if it is working for you now.

**Comment by venalaine** [comment]
Sorry I haven't been actively following development during the past few months but now I tried this (and Sega Rally too) with recent build and can confirm the issue is gone. I will close the bug.
