### ISSUE TITLE
Akumajou Dracula X - Gekka no Yasoukyoku (English v1.021) hang after defeating Succubus

### ISSUE THREAD

**Issue by faragon** [MiSTer-devel/Saturn_MiSTer#38]
The game works incredibly well, e.g. more than 9h for reaching over 100% of the map, and the point when the problem happens is not a total hang, but something like a forever-wait loop, with the image being animated (see steps and video below).

**Version (or build number)**

20231018

**Single or Dual SDRAM?**

Single (128MB), v2.9, stable at >140MHz

**Steps to reproduce**

1.    load savegame from the .zip to /media/fat/saves/Saturn [Akumajou Dracula X - Gekka no Yasoukyoku (English v1.021).zip](https://github.com/srg320/Saturn_MiSTer/files/13169487/Akumajou.Dracula.X.-.Gekka.no.Yasoukyoku.English.v1.021.zip)
2.    load Akumajou Dracula X - Gekka no Yasoukyoku (English v1.021)
3.    start the game, and load the save game with 102.6% of the game, starting in the room at the right of the save game room:
![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/518864/de5675ca-5206-4295-a7a9-13004484ca31)

4.    enter into the pink false savegame, starting the "Nightmare" screen, and defeat the enemy ("Succubus").

**Expected Behavior**

It should work like in the following YouTube video, i.e. exit the scene after defeating Succubus: https://www.youtube.com/watch?v=BisuaEUlqOk

**Actual Behavior**

After Succubus being defeated, the music ends, and there's movement, but it gets stuck. It happens both if pressing start or A for speeding-up the scene, and also waiting until it finishes by itself. See mp4 video I've just made it, it is a short video, but it is like that, but in an infinite loop. The video works, but the audio stops. Just in case for you it means something

https://user-images.githubusercontent.com/518864/278116349-b79dfbf8-fed7-41ad-acc7-453f4186cdd0.mp4

Observations:

-  it behaves the same having the holy water secondary weapon instead of the clock.
-  it behaves the same disabling (debug): SSCP {Direct|DSP} sound / CD audio

**Comment by Vampier** [comment]
this doesn't seem to be a core issue but an issue with the version translation. I played up till that point and had the same issue (that's how I ended up here). However it seems that when renaming the save file (memory card) to be used for the original version yields not the same result. I just picked up the 1st of the ring for the clock tower after the fight in the Japanese version. 
[Save Files.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14128856/Save.Files.zip)

**Comment by Vampier** [comment]
this is an issue with the core - Colosseum entrance 

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/12684428/44667394-088d-4b12-a654-8a0bfee4e233

**Comment by Vampier** [comment]
As on 2024/02/02 release the slowdown is gone for the area above.  

@faragon ok to close this ticket?

**Comment by faragon** [comment]
@Vampier Sure, closing it. I reported this just in case.

P.S. thank you for your https://vampier.net/N64/ ☺
