### ISSUE TITLE
Sonic 3D - VDP2 NBG2 issues

### ISSUE THREAD

**Issue by kerunaru** [MiSTer-devel/Saturn_MiSTer#43]
In zones with fog effect (Rusty Ruin, Diamond Dust and Volcano Valley) having VDP2 NBG2 enabled causes VDP2 NBG0 layer transparent.

After beating a zone of this type, some graphical corruption remains in the next zone if it is a no-fog one. This glitch makes VDP2 NBG0 layer transparent where both layers overlap. This behaviour only finishes when you enter a special stage.

**Comment by real-amano** [comment]
Is this still am issue?

**Comment by kerunaru** [comment]
@real-amano nope. It seems to be solved in the current release :D
