### ISSUE TITLE
Grandia Battle Screens

### ISSUE THREAD

**Issue by Zhan85** [MiSTer-devel/Saturn_MiSTer#48]
When entering into a battle scene in Grandia the graphics and sprites become out of place or invisible.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/9265f5434b9ae9989f955946a8592902c8742dbb

Please test the core revision 20241018 and update/close the issue if necessary.

**Comment by Kuba-J** [comment]
![obraz](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/95412885/4d67f58e-e390-4054-b680-c9eba6026c35)

looks great :) thanks!

**Comment by Zet-sensei** [comment]
@Zhan85 Could you test once more & update or even close the issue ?
Thanks.

**Comment by Zhan85** [comment]
> @Zhan85 Could you test once more & update or even close the issue ? Thanks.

Battle scenes are fixed, yes!  There are still many slow down issues when you first move into a new area as well as various graphical glitches throughout the game.

Definitely playable at this point though!  Thanks for your work on this.

**Comment by Kuba-J** [comment]
@Zhan85 please close the issue :) thanks!
