### ISSUE TITLE
Groove on Fight: Gōketsuji Ichizoku 3 Garbled Background Layer

### ISSUE THREAD

**Issue by SeanerGame** [MiSTer-devel/Saturn_MiSTer#49]
On every stage, some of the background layers are glitches. Works fine otherwise.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f519e4d446e0692c4b3fcdd202bf6c8aaf5cd2b7

**Comment by SeanerGame** [comment]
Fixed
