### ISSUE TITLE
US Resident Evil: Chance of crashing during dialog/cutscene

### ISSUE THREAD

**Issue by Isles487** [MiSTer-devel/Saturn_MiSTer#50]
With latest build, have random crashes so far during cutscenes, 3 encountered during Chris's campaign:

First playthrough: after letting Rebecca practice the piano, going to main hall, and returning, I entered the piano room and the cutscene began to start (black bars on top and bottom applied), but the camera angle never switched and it remained that stuck.

Playthroughs 2 and 3: freezes during opening dialog. Generally as another line was about to load, again, Chris's campaign.

**Comment by Isles487** [comment]
To add: core itself does not freeze. In one instance, during the opening cutscene as Jill, when it was time for Jill and Barry to head towards the dining room, the cutscene stopped advancing and instead Barry kept running in a circle in and out of the frame.

**Comment by Kuba-J** [comment]
Shuould be fixed , test core 20240229 + latest unstable mister main [MiSTer.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14450787/MiSTer.zip). Please retest.

**Comment by Isles487** [comment]
@Kuba-J Thank you for the heads-up. I played through about 3/4 of Jill's scenario and so far, so good. I think I will allow a day or two for anyone else to chime in, just in case anyone encounters any more occurrences - though I'm not expecting it. At that point I will close.
