### ISSUE TITLE
The Legend of Sword and Fairy (Chinese: 仙劍奇俠傳; pinyin: Xiānjiàn Qíxiá Zhuàn) cannot play

### ISSUE THREAD

**Issue by mhmetalheart** [MiSTer-devel/Saturn_MiSTer#54]
The Legend of Sword and Fairy (Chinese: 仙劍奇俠傳; pinyin: Xiānjiàn Qíxiá Zhuàn)
newest core.
game can start, but after CG, the character will keep lay on the ground won't get up. Background image all in black, game cannot continue.

**Comment by mhmetalheart** [comment]
newest version: 241113 tested:
Senken Kigyouden (Japan): this is the title in Japanese. Now it move a little bit step in, the dialogue bump up. But after that, it cannot control the character stand up. BUT NOT EVERYTIME. When I reset, it still like last version, black background. Nothing happened.
Xianjian Qixiazhuan (Taiwan): This is the Asia Chinese Verson. still black.

**Comment by Zet-sensei** [comment]
Please retest with the latest core version, some fixes have been applied since version 20240204.
Thanks.

**Comment by mhmetalheart** [comment]
The core seems very unstable. It can stand up, game can play. But next update will be lay down again. I tested nearest 6 unstable builds.
