### ISSUE TITLE
Vandal Hearts - Ushinawareta Kodai Bunmei (Japan) // Can't see the selection mask on main title screen

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#60]
A mask effect seems to be missing for the selection on the main menu (title screen).

Core 20240110

Expected result on a real Saturn system.
![Vandal](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/52127625/6167836f-cd70-4cf2-bae3-cf5a0c8d542a)

**Comment by Kuba-J** [comment]
fixed , core 20240120 , thanks! :)

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/75a179df848c279e135c85f27c0ccc08360159ec
