### ISSUE TITLE
Street fighter Zero 3 - The sound disappears and the game slows down

### ISSUE THREAD

**Issue by ZmaxAldrey** [MiSTer-devel/Saturn_MiSTer#63]
At the end of the game's introduction. the sound disappears. And when we choose the character in arcade mode in the second fight, the game becomes slow and has no sound.

Steps: 
- Turn on the game and let the intro

Results: 
- The game goes silent at the end of the intro.

**Comment by Zet-sensei** [comment]
Can't reproduce on my system, even after reading some users with the problem.

DualRAM 128MB v2.9, core 20240110, stable Main 20240110
CHD version done with CHDMAN 0.261, coming from my original copy extracted in BIN+CUE (Redump) format.
Game on USB stick.
Hi-Saturn Free region BIOS.

Could you update the issue with your MiSTer system info too?
Just to have some more info and maybe find where the issue could be - by correlation between testers.

**Comment by ZmaxAldrey** [comment]
Hello!!

CHD version done with CHDMAN 0.261, coming from my original copy extracted in BIN+CUE (Redump) format. (The same)
Game on USB stick . (The problem occurs on both the memory card and an external hard drive)
Hi-Saturn Free region BIOS. (The same)

*Attached images

OBS: I also tested it on the latest version available yesterday on January 10, 2024

https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/29a45dfd-897d-44fa-a89c-fa21f16315e7


https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/2e1a047d-9531-4991-b01e-e1a8e65b7ec5

![MiSTer](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/c8780800-a7bb-4ef7-a98e-446a8de168ef)

**Comment by Kuba-J** [comment]
for me it works without problems, sdram v2.9 , micro sd card sandisk 256gb extreme, last core and mister main

**Comment by bootsector** [comment]
Probably related to https://github.com/MiSTer-devel/Saturn_MiSTer/issues/33

**Comment by Zet-sensei** [comment]
Please check once more on the last core revision (20240113).
Some games seem to be working OK with a recent DDRAM controller rework commit.

**Comment by ZmaxAldrey** [comment]
Tested on the latest core 'sega saturn 24-01-13' and the error persists

**Comment by ZmaxAldrey** [comment]
Update: Tested on the latest core unstable 'sega saturn 24-01-18' and the error persists.

**Comment by bootsector** [comment]
@ZmaxAldrey please give us an update with the latest unstable version. Thanks!

**Comment by ZmaxAldrey** [comment]
The sound error and slowness still occur in version 24-03-07.

**Comment by ZmaxAldrey** [comment]
The issue has been fixed. Core Unstable 24.03.15

Tks a lot!!

**Comment by ZmaxAldrey** [comment]
After 8 minutes of playing, the game shows slowdowns again, even when selecting the 4m RAM card and the Japanese bios. I also tested in other bios and the same problem occurs. Reopening the bug.

**Comment by ZmaxAldrey** [comment]
The sound error and slowness still occur in version 23-04-07.

**Comment by ZmaxAldrey** [comment]
The sound error and slowness still occur in version 23-04-20.

**Comment by srg320** [comment]
@ZmaxAldrey, what version of sdram module you have installed?

**Comment by ZmaxAldrey** [comment]
Hi @srg320 !!

This:

![01](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/ab95820a-89b6-4a6e-841a-84c6d12c8414)
![02](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/9fe7adc6-7ced-49d8-a5fc-be6050ed0317)
![03](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/8c2c0747-a361-4ad8-8974-12f4d5e2fc19)
![04](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/ac0cea52-2be2-4521-994e-003066da6eb6)

**Comment by srg320** [comment]
Ok. Try this build.
[Saturn.zip](https://github.com/user-attachments/files/15788811/Saturn.zip)

**Comment by ZmaxAldrey** [comment]
@srg320 Now it's perfect. Thank you very much!!
I'm going to get this version and test the others that weren't ok for me.

THANKS A LOT!!!

**Comment by ZmaxAldrey** [comment]
@srg320 Now it's perfect. Thank you very much!!
I'm going to get this version and test the others that weren't ok for me.

THANKS A LOT!!!
