### ISSUE TITLE
SEGA AGES - After Burner // Barely Any Sound

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#67]
As of the January 13th 2024 build, the SEGA AGES release of After Burner has almost no sound. It does occasionally make a high pitch glitchy screech, like it's _trying_ to produce sound, but otherwise nothing comes out. Tested on both single and double RAM builds with a 2.9 RAM setup.

**Comment by InfernoHabanero** [comment]
The February 17th build partially fixed the audio problem. Now audio does play, but there is an issue where the audio eventually breaks after a few seconds.

**Comment by METR0lD** [comment]
Today's build brought the music back in the game. But there are no sound effects still. Big improvement, but not quite there yet!

**Comment by METR0lD** [comment]
Today's build fixed the missing sound effects! Audio sounds perfect now as far as I can tell. Amazing work srg320!

**Comment by JaeOfMordor** [comment]
@InfernoHabanero please test and close

**Comment by real-amano** [comment]
Video Game Esoterica tested it again: https://youtu.be/bjUj5CL6wvk?si=KB1zKaiL6j7BQoS8

Seems fine now. @InfernoHabanero, can you confirm.
