### ISSUE TITLE
Puyo Puyo 2 // Single Player Mode Menu Isn't Darkening The Unhighlighted Modes

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#68]
![Screenshot 2024-01-13 13-27-35](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/29affb16-3e2a-4850-a507-59f3dcb5e144)

As of the January 13th 2024 build, there is a bug where in the the single player mode selection menu, it isn't properly highlighting your choice. Normally the modes not selected are supposed to be darked, but it simply doesn't happen, so it's not obvious what mode you're highlighting if you can't read the description. This was actually fixed in a much older build, but then it regressed later on and has been like this for months now.

RAM 2.9 setup, both single and dual RAM build effected.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-01-20 13-48-46](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/513ae5e1-a73f-49ee-bc5e-2de2cfb1789e)

The January 20th 2024 build fixed the problem! Closing this for now.

**Comment by InfernoHabanero** [comment]
![Screenshot 2024-02-10 12-33-05](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/117416952/1249381c-16c9-49cb-81a5-bc58832ed3a0)
The February 10th 2024 build broke the transparency again.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/e411aba5bfb3d305c97518c50b8816d72e54bdcd
