### ISSUE TITLE
Manx TT SuperBike (Europe) // Freezes after selecting the transmission type or before entering the first race

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#73]
Tested on core 20241013 Dual RAM.
'Europe' region forced on multi-region hacked Hi-Saturn BIOS and also tested with European BIOS.

I need to restest on the NTSC version of the game later today for comparison.
That version of the game used to be problematic on SW emulators

EDIT : Regression on core 20240113.

**Comment by Kuba-J** [comment]
NTSC-U version also crashes

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/f041046d1f986a4140c19249d977ac7323b089c0
