### ISSUE TITLE
Primal Rage (USA) // SMPC bug - Cannot boot

### ISSUE THREAD

**Issue by Zet-sensei** [MiSTer-devel/Saturn_MiSTer#74]
The game refuses to load on my systems (Single and Dual RAM).
I tried to force a region, multiple BIOS versions.

The game goes back systematically to the BIOS after the SEGA logo, but detects the disc as a valid Saturn one inside the BIOS menu.
Even with a full fresh reboot of the core and the MiSTer system.

EDIT : I asked for a comparative test with other users, as the game booted up on previous builds with just a broken intro FMV.
Searching eventually for a regression.

EDIT 2 : Kuba-J tested the game on Discord & could report the game tends to boot for a first time, and same result as mine when trying to launch the game once again on his system.

**Comment by Zet-sensei** [comment]
In addition.

The JPN version boots, but no controller response at all on that version of the game.

EDIT : I've asked for a comparative tests to other users on Discord and will update the issue if necessary.

**Comment by Zet-sensei** [comment]
I've seen a note on Mednafen 1.28.00 that should give us a hint about the problem.

October 5, 2021:
	SS: Implemented a delay when the SMPC joystick read process is aborted due to time over or due to the Break bit being 1, per tests on a SS, and fixed
	timing granularity issues with the processing of the Break/Continue bits; fixes unresponsive input in "Discworld", and abort to CD player screen in the
	USA and Europe releases of "Primal Rage".
	
Seems to be related to issue https://github.com/MiSTer-devel/Saturn_MiSTer/issues/76

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1d100057653039cb1096cfd524b13031fc8fa8f3 , thanks srg320 !

**Comment by Zet-sensei** [comment]
The issue is confirmed to be back & detected on version 2026-04-03 Dual RAM.

EDIT : I will check the compilation of the core & some previous releases later tomorrow.

**Comment by Zet-sensei** [comment]
After a check with kuba-J on when the issue was back, that commit on the SMPC here could maybe be at fault.
https://github.com/MiSTer-devel/Saturn_MiSTer/commit/5ad4977c76fa485c1eacac2b9d3bba55d891469d

UPDATE: After reverting the change made on 2025-11-04 (with that mentioned commit) to the SMPC source code of 2026-04-03 (Dual RAM), the game is working again, but several tests are now broken.

**Comment by Zet-sensei** [comment]
Fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/714c80621c06552d15a88fe5ee6e2cb7bf636abc
