### ISSUE TITLE
The King of fighters 96 - Characters break graphically during the fight

### ISSUE THREAD

**Issue by ZmaxAldrey** [MiSTer-devel/Saturn_MiSTer#80]
Precondition:
 - Turn on the game

Steps
 - Select the Japan team (My example)
 - Visualize the second player (CPU)

Expected results:
 -  Characters without breaking

Obtained results:
 -  Characters break graphically

Attached image:

![kof96-1](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/1b98c19c-274e-41dd-a7e7-1a9007dd1ed3)
![kof96-2](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/49198852-f866-4f46-86e2-fd47a22541e4)

**Comment by real-amano** [comment]
@ZmaxAldrey can you re-test with the information above and close your king of fighters issues?

**Comment by ZmaxAldrey** [comment]
It's works with 1mb. Tks a lot guys!!

**Comment by ZmaxAldrey** [comment]
It's works with 1mb. Tks a lot guys!!
