### ISSUE TITLE
Real bout Garow densetsu - Characters break graphically during the fight

### ISSUE THREAD

**Issue by ZmaxAldrey** [MiSTer-devel/Saturn_MiSTer#81]
**Precondition:**
- Turn on the game

**Steps**
- Select the Japan team (My example)
- Visualize the second player (CPU)

**Expected results:**
- Characters without breaking

**Obtained results:**
- Characters break graphically

![realbout1](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/120676123/589d2e82-8378-4065-990a-2f1a68c96f1b)

**Comment by Zet-sensei** [comment]
SNK games don't like the 4MB RAM cartridge option, otherwise they break like that.
You must force the 1MB option on the core.

Same for Metal Slug and KOF games.

Could you please retry with the 1MB option and update the issue ?
Thanks.

**Comment by real-amano** [comment]
@ZmaxAldrey please test again and close that issue.

**Comment by ZmaxAldrey** [comment]
The bug still occurs. Core Saturn Unstable 24.03.15

**Comment by ZmaxAldrey** [comment]
It's works with 1mb. Tks a lot guys!!

**Comment by ZmaxAldrey** [comment]
It's works with 1mb. Tks a lot guys!!
