### ISSUE TITLE
Several Games with FMV and audio issues with 2.4 and 2.5 SDRAM

### ISSUE THREAD

**Issue by foxp4v** [MiSTer-devel/Saturn_MiSTer#85]
Hello, with MiSTer setup (128 mb 2.4 SDRAM), i have several issues with games likes Clockwork Knight, Panzer Dragoon 1 and Zwei that have semi freeze on the FMV intro (pressing start the games goes on) and sound issues where audio disappears and come back. Other games with audio issues are the common Sega Rally, Nights into Dreams, Radiant Silvergun, Virtua Fighter 2 and probably others. There are chances that Will be fixed for those Who have old revision of SDRAM or Will be forced to upgrade? Thank for your hard work and stay safe. Bye.

**Comment by Kuba-J** [comment]
https://github.com/MiSTer-devel/Saturn_MiSTer/issues/33#issuecomment-2160567461 - please retest with new core

**Comment by foxp4v** [comment]
Tested Yesterday. All issues relative to RAM seems solved.

**Comment by real-amano** [comment]
But the FMV issues persist? Can you adapt the thread title to reflect this?

**Comment by real-amano** [comment]
@foxp4v , if no issues persist, I guess that the bug can be closed then.

**Comment by foxp4v** [comment]
> @foxp4v , if no issues persist, I guess that the bug can be closed then.

The core has not been released in the stable branch, i think it's better to wait until then.

**Comment by real-amano** [comment]
@foxp4v it is released now to stable
