### ISSUE TITLE
Rockman X4 randomly crashes during the bosses' speeches

### ISSUE THREAD

**Issue by ldoryu09** [MiSTer-devel/Saturn_MiSTer#87]
The game randomly crashes during the bosses' speeches with character X, which happens a lot. In the American version, without the bosses' dialogues, the music sometimes stops and returns when the scene is completed. The same problem occurs in the final bosses as in the JP version, in the American version, due to the bosses having audio dialogues.

**Comment by ldoryu09** [comment]
Rockman X4 JP Dialogue Boss crashes - Core: Saturn_unstable_20240120_18aa6e


https://github.com/MiSTer-devel/Saturn_MiSTer/assets/125805945/2804cbfb-fcad-4853-8a9a-54887c54fbb9

**Comment by Kuba-J** [comment]
I cannot reproduce this issue , tested US and JAP version

**Comment by ldoryu09** [comment]
What could it be then? :/

**Comment by ldoryu09** [comment]
I added 3 Saves to Final Weapon for other testers and srg320.
[Sega Saturn Saves.zip](https://github.com/MiSTer-devel/Saturn_MiSTer/files/14181761/Sega.Saturn.Saves.zip)

**Comment by Zet-sensei** [comment]
There was some recent updates on Main MiSTer (20240304 unstable) and the core (29022024).
I can't seem to reproduce the bug at all with that configuration on my Single and Dual RAM systems.
Tested 3 times, beating all bosses each time.

I've tested with the save files on the Final Weapon stage - with all the returning bosses (boss rush).

**Comment by real-amano** [comment]
@ldoryu09 , can you re-test it and close the bug if it is fixed?

**Comment by ldoryu09** [comment]
I tested Rockman X4 on CORE Saturn_unstable_20240307_15b8c0 and finished the game twice.
In this core, the problem of freezing in bosses' speeches is no longer present. Problem fixed.
