### ISSUE TITLE
Abnormally Low Volume In Specific Games (Saturn Bomberman, Princess Maker 2, etc.)

### ISSUE THREAD

**Issue by InfernoHabanero** [MiSTer-devel/Saturn_MiSTer#9]
Some games have an issue where the overall volume levels are lower than they should be. Examples include Saturn Bomberman (NTSC-U), Princess Maker 2 (NTSC-J), Magical Drop (NTSC-J), and Sakura Taisen - Hanagumi Taisen Columns (NTSC-J). One thing they have in common is that there is an auditable popping noise before the audio plays, implying there is a bug with the core loading the audio.

This is the case as of the official October 10th 2023 build.

**Comment by SegaSnatcher** [comment]
Virtua Fighter 2 audio seems super low as well.

**Comment by InfernoHabanero** [comment]
> Virtua Fighter 2 audio seems super low as well.

I've notice this being especially bad with the SEGA fighting games in general. Fighting Vipers, Fighters Megamix, etc. all have extremely low volume that you need to crank up the volume to the max to get anything decent.

**Comment by Shogun38** [comment]
This is occurring in Soukyuu Gurentai (J) (v2.000) for me as well.

**Comment by Zet-sensei** [comment]
General sounds levels are getting better with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/762210a7adaf641f5b6a9d3068ec7efc640b901a

But I have some pretty clipped sound effects on games like Asuka 120% and Virtua Fighter (like the commentator voices) as quick examples.

**Comment by Zet-sensei** [comment]
Some games like Virtua Fighter 2 have some strange noises when doing their initial loading - before the main menu.

**Comment by Zet-sensei** [comment]
On core version 20240229, the noises when loading Virtua Fighter 2 can't be heard anymore.

But some sound effects on multiple games are really scratchy and overpowered by some operations by the SCSP DSP.
Disabling (temporarily) the DSP sound on the Debug mode removes that issue.

**Comment by Kuba-J** [comment]
This is very audible in Virtual On, explosions and gunfire cause a lot of sound distortion

**Comment by Kuba-J** [comment]
fixed https://github.com/MiSTer-devel/Saturn_MiSTer/commit/577c12f1f3c379f9cae8e4fdf6f69c8174d887c5

**Comment by Kuba-J** [comment]
recent improvements have really made the core sound great , thanks srg320!
