### ISSUE TITLE
Shienryuu (JP) Sprites layer is rotated 90 degrees clockwise.

### ISSUE THREAD

**Issue by Jimmy2x2x** [MiSTer-devel/Saturn_MiSTer#91]
Shienryuu (JP) Sprites layer is rotated 90 degrees clockwise.

So a sprite that should appear at the bottom edge
, appears at the left edge.

Start a game to see it.

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/1805cf708e3bbdadc43810b4b379b82b36dd3538.

**Comment by Jimmy2x2x** [comment]
Fantastic news, thank you!

**Comment by Shrapnel21** [comment]
> Fantastic news, thank you!

Hey, you've got a MiSTer, that's cool! I can't afford one. =(
By any chance, did you get it with those 5000€ you got a few years ago?
You remember, do you?
