### ISSUE TITLE
Sakura Wars: FMV playback issue

### ISSUE THREAD

**Issue by JaeOfMordor** [MiSTer-devel/Saturn_MiSTer#92]
the video playback of all in-game cutscenes is much darker than it appears on original hardware.

**Comment by JaeOfMordor** [comment]
![My_Great_Game_-_My_Great_Capture_2024-01-23_09-23-38](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/998e0d32-1aa8-448c-8a5e-47b54577d4e5)

this was taken from the MiSTer over RGBS scart

**Comment by JaeOfMordor** [comment]
![My_Great_Game_-_My_Great_Capture_2024-01-23_09-25-33](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/114522512/150572fa-ac66-4388-aa90-a9463d610583)

this was taken from the Saturn over RGBS scart

**Comment by Zet-sensei** [comment]
We can also see a thin corrupted line on the right side of the FMV.

**Comment by Zet-sensei** [comment]
FMV brightness is correct now (tested with core version 20240212).

Remains a small line on the right side of the FMV that is incorrectly rendered.

**Comment by real-amano** [comment]
Wow, even that single corrupted line got a separate commit to fix it today ;)

**Comment by JaeOfMordor** [comment]
> Wow, even that single corrupted line got a separate commit to fix it today ;)
> 
> @JaeOfMordor can you confirm it is fixed and close the bug?

can now personally confirm it's all good now.

closing issue
