### ISSUE TITLE
NBA JAM Tournament Edition (USA) // Team Selection Screen Flickering

### ISSUE THREAD

**Issue by vmicka72** [MiSTer-devel/Saturn_MiSTer#95]
Core : 20240120

During the team selection the screen is flickering.

![image](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/42602422/c99052af-4d8e-408a-afb9-f3858c226f2d)

**Comment by Zet-sensei** [comment]
Should be fixed with commit https://github.com/MiSTer-devel/Saturn_MiSTer/commit/15f19290f95b35dc9cde7982ad43e619b1cee77d

Please restest with core version 20240206.
Thanks.

**Comment by vmicka72** [comment]
Fixed in 20240206 release.

**Comment by vmicka72** [comment]
Fixed in 20240322 release.
