### ISSUE TITLE
Problem with shading  (Tomb Raider, Powerslave, Pandemonium )

### ISSUE THREAD

**Issue by Kuba-J** [MiSTer-devel/Saturn_MiSTer#96]
The shading problem can be seen in several games, on video Tomb Raider, Powerslave and Pandemonium

https://youtu.be/VK2IrqxQPCU

**Comment by LuckyNES** [comment]
Example on nights:
![mister](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/104242031/78c4c123-c13e-4e92-9fab-77ea90997029)
![real_saturn](https://github.com/MiSTer-devel/Saturn_MiSTer/assets/104242031/9aa2770b-473f-4c23-ae55-dbdda2458d8b)

**Comment by LuckyNES** [comment]
I think only certain quads/polygons are flipped.

**Comment by Zet-sensei** [comment]
A new official version of the core is ready for today.
With essential Gouraud shading fixes.

Please test once more with the lastest Unstable Main MiSTer file + the stable core version 20240323 & update the issue as possible.
Thanks.

**Comment by Kuba-J** [comment]
Fixed all, core 20240323
